-- Demo seed: company co_1 (Atmata Trading Co., KW) only.
-- Generated by scripts/generate-demo-seed.ts from src/mocks/seed/*.
-- Preserves mock ids so UI / cross-document links stay intact.
-- Idempotent via ON CONFLICT DO NOTHING. Kuwait demo company only.
-- Skips auth-dependent rows that need real auth.users (approval_requests,
-- notifications). audit_events are seeded with "by" = NULL.


-- ---------------------------------------------------------------------------
-- companies
-- ---------------------------------------------------------------------------

INSERT INTO public.companies (id, name, tax_profile, base_currency, vat_number, status, plan)
VALUES
  ('co_1', 'Atmata Trading Co.', 'KW', 'KWD', 'KW100100100', 'active', 'pro')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- currencies
-- ---------------------------------------------------------------------------

INSERT INTO public.currencies (id, company_id, code, name, symbol, decimal_places, active)
VALUES
  ('cur_co_1_kwd', 'co_1', 'KWD', 'Kuwaiti Dinar', 'د.ك', 3, true),
  ('cur_co_1_sar', 'co_1', 'SAR', 'Saudi Riyal', 'ر.س', 2, true),
  ('cur_co_1_aed', 'co_1', 'AED', 'UAE Dirham', 'د.إ', 2, true),
  ('cur_co_1_usd', 'co_1', 'USD', 'US Dollar', '$', 2, true)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- branches
-- ---------------------------------------------------------------------------

INSERT INTO public.branches (id, company_id, name)
VALUES
  ('br_1', 'co_1', 'Kuwait HQ')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- warehouses
-- ---------------------------------------------------------------------------

INSERT INTO public.warehouses (id, company_id, branch_id, code, name)
VALUES
  ('wh_1', 'co_1', 'br_1', 'MAIN', 'Main DC — Shuwaikh'),
  ('wh_2', 'co_1', 'br_1', 'SHOWROOM', 'Showroom — Salmiya')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- locations
-- ---------------------------------------------------------------------------

INSERT INTO public.locations (id, company_id, warehouse_id, code, name)
VALUES
  ('loc_1', 'co_1', 'wh_1', 'A-01', 'Aisle A — Rack 01'),
  ('loc_2', 'co_1', 'wh_1', 'B-03', 'Aisle B — Rack 03'),
  ('loc_3', 'co_1', 'wh_2', 'FLOOR', 'Showroom floor')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- tax_codes (KW for co_1)
-- ---------------------------------------------------------------------------

INSERT INTO public.tax_codes (id, company_id, jurisdiction, code, name_en, name_ar, rate, is_input, is_output)
VALUES
  ('tax_kw_vat_5', 'co_1', 'KW', 'KW-VAT-5', 'Kuwait VAT 5%', 'ضريبة القيمة المضافة الكويت 5٪', 0.05, true, true),
  ('tax_exempt', 'co_1', 'KW', 'EXEMPT', 'Tax exempt', 'معفى من الضريبة', 0, false, false)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- payment_terms
-- ---------------------------------------------------------------------------

INSERT INTO public.payment_terms (id, company_id, code, name_en, name_ar, net_days)
VALUES
  ('pt_net30', 'co_1', 'NET30', 'Net 30', 'صافي 30 يوم', 30),
  ('pt_net60', 'co_1', 'NET60', 'Net 60', 'صافي 60 يوم', 60),
  ('pt_cod', 'co_1', 'COD', 'Cash on delivery', 'الدفع عند الاستلام', 0)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- accounts (mock chart of accounts)
-- ---------------------------------------------------------------------------

INSERT INTO public.accounts (id, company_id, code, name, type, active)
VALUES
  ('acc_inv', 'co_1', '1100', 'Inventory', 'asset', true),
  ('acc_grir', 'co_1', '2110', 'GR/IR clearing', 'liability', true),
  ('acc_ap', 'co_1', '2100', 'Accounts payable', 'liability', true),
  ('acc_input_vat', 'co_1', '1450', 'Input VAT recoverable', 'asset', true),
  ('acc_bank_nbk_kwd', 'co_1', '1010', 'NBK current — KWD', 'asset', true),
  ('acc_ar', 'co_1', '1200', 'Accounts receivable', 'asset', true),
  ('acc_revenue', 'co_1', '4000', 'Revenue — equipment', 'revenue', true),
  ('acc_output_vat', 'co_1', '2150', 'Output VAT payable', 'liability', true),
  ('acc_cogs', 'co_1', '5000', 'Cost of goods sold', 'expense', true),
  ('acc_inv_loss', 'co_1', '5900', 'Inventory loss', 'expense', true)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- account_mappings (mock account ids)
-- ---------------------------------------------------------------------------

INSERT INTO public.account_mappings (id, company_id, mapping_key, account_id)
VALUES
  ('map_co_1_bank', 'co_1', 'bank', 'acc_bank_nbk_kwd'),
  ('map_co_1_accounts_receivable', 'co_1', 'accounts_receivable', 'acc_ar'),
  ('map_co_1_accounts_payable', 'co_1', 'accounts_payable', 'acc_ap'),
  ('map_co_1_inventory', 'co_1', 'inventory', 'acc_inv'),
  ('map_co_1_cogs', 'co_1', 'cogs', 'acc_cogs'),
  ('map_co_1_revenue', 'co_1', 'revenue', 'acc_revenue'),
  ('map_co_1_input_vat', 'co_1', 'input_vat', 'acc_input_vat'),
  ('map_co_1_output_vat', 'co_1', 'output_vat', 'acc_output_vat'),
  ('map_co_1_inventory_adjustment', 'co_1', 'inventory_adjustment', 'acc_inv_loss'),
  ('map_co_1_goods_received_not_invoiced', 'co_1', 'goods_received_not_invoiced', 'acc_grir')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- bank_accounts
-- ---------------------------------------------------------------------------

INSERT INTO public.bank_accounts (id, company_id, name, iban, currency, account_id, active)
VALUES
  ('bank_1', 'co_1', 'NBK Current — KWD', 'KW81NBOK0000000000001234560101', 'KWD', 'acc_bank_nbk_kwd', true)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- fiscal_periods
-- ---------------------------------------------------------------------------

INSERT INTO public.fiscal_periods (id, company_id, year, month, "start", "end", status)
VALUES
  ('fp_2026_01', 'co_1', 2026, 1, '2026-01-01', '2026-01-31', 'hard_closed'),
  ('fp_2026_02', 'co_1', 2026, 2, '2026-02-01', '2026-02-28', 'hard_closed'),
  ('fp_2026_03', 'co_1', 2026, 3, '2026-03-01', '2026-03-31', 'soft_closed'),
  ('fp_2026_04', 'co_1', 2026, 4, '2026-04-01', '2026-04-30', 'open'),
  ('fp_2026_05', 'co_1', 2026, 5, '2026-05-01', '2026-05-31', 'open'),
  ('fp_2026_06', 'co_1', 2026, 6, '2026-06-01', '2026-06-30', 'open'),
  ('fp_2026_07', 'co_1', 2026, 7, '2026-07-01', '2026-07-31', 'open'),
  ('fp_2026_08', 'co_1', 2026, 8, '2026-08-01', '2026-08-31', 'open'),
  ('fp_2026_09', 'co_1', 2026, 9, '2026-09-01', '2026-09-30', 'open'),
  ('fp_2026_10', 'co_1', 2026, 10, '2026-10-01', '2026-10-31', 'open'),
  ('fp_2026_11', 'co_1', 2026, 11, '2026-11-01', '2026-11-30', 'open'),
  ('fp_2026_12', 'co_1', 2026, 12, '2026-12-01', '2026-12-31', 'open')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- products
-- ---------------------------------------------------------------------------

INSERT INTO public.products (id, company_id, sku, name, uom, tax_code_id, costing_method, lot_tracked, purchasable, sellable, default_purchase_price, default_sale_price)
VALUES
  ('prod_1', 'co_1', 'RM-01', 'Resin 25kg', 'BAG', 'tax_kw_vat_5', 'AVG', false, true, false, 12.4, 0),
  ('prod_2', 'co_1', 'PKG-L', 'Carton large', 'PCS', 'tax_kw_vat_5', 'AVG', false, true, false, 0.35, 0),
  ('prod_3', 'co_1', 'LBL-T', 'Thermal label roll', 'ROLL', 'tax_kw_vat_5', 'AVG', false, true, false, 8.75, 0),
  ('prod_4', 'co_1', 'SKU-104', 'Display cooler — 2 door', 'PCS', 'tax_kw_vat_5', 'AVG', true, true, true, 620, 890),
  ('prod_5', 'co_1', 'SKU-220', 'Barcode scanner kit', 'PCS', 'tax_kw_vat_5', 'AVG', false, true, true, 28, 42.5)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- customers
-- ---------------------------------------------------------------------------

INSERT INTO public.customers (id, company_id, name, vat_number, credit_limit, exposure, payment_status, credit_score, active)
VALUES
  ('cust_1', 'co_1', 'Kuwait Retail Co.', 'KW200200200', 25000, 18420, 'current', 'A', true),
  ('cust_2', 'co_1', 'Gulf Foods WLL', 'KW200300300', 40000, 38900, 'overdue_14', 'B', true),
  ('cust_3', 'co_1', 'City Pharmacy', 'KW200400400', 15000, 14200, 'current', 'A', true),
  ('cust_4', 'co_1', 'Project Alpha JV', 'KW200500500', 60000, 62500, 'on_hold', 'C', true)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- suppliers
-- ---------------------------------------------------------------------------

INSERT INTO public.suppliers (id, company_id, name, vat_number, bank_account, payment_term_id, wht_applicable, wht_rate, active)
VALUES
  ('sup_1', 'co_1', 'PetroChem Gulf', 'KW300100100', 'KW81NBOK0000000000999100', 'pt_net30', false, NULL, true),
  ('sup_2', 'co_1', 'PackLine KW', 'KW300200200', 'KW81NBOK0000000000999200', 'pt_net30', false, NULL, true),
  ('sup_3', 'co_1', 'PrintHub', 'KW300300300', 'KW81NBOK0000000000999300', 'pt_net60', true, 0.05, true),
  ('sup_4', 'co_1', 'Gulf Supplies WLL', 'KW300400400', 'KW81NBOK0000000000999400', 'pt_net30', false, NULL, true)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- fx_rates
-- ---------------------------------------------------------------------------

INSERT INTO public.fx_rates (id, company_id, base_currency, quote_currency, rate, rate_date, source)
VALUES
  ('fx_co_1_1', 'co_1', 'USD', 'KWD', 0.307, '2026-05-15', 'manual'),
  ('fx_co_1_2', 'co_1', 'USD', 'SAR', 3.75, '2026-05-15', 'manual'),
  ('fx_co_1_3', 'co_1', 'USD', 'AED', 3.673, '2026-05-15', 'manual'),
  ('fx_co_1_4', 'co_1', 'KWD', 'USD', 3.258, '2026-05-15', 'manual'),
  ('fx_co_1_5', 'co_1', 'KWD', 'SAR', 12.215, '2026-05-15', 'manual'),
  ('fx_co_1_6', 'co_1', 'KWD', 'AED', 11.966, '2026-05-15', 'manual'),
  ('fx_co_1_7', 'co_1', 'SAR', 'KWD', 0.0819, '2026-05-15', 'manual'),
  ('fx_co_1_8', 'co_1', 'AED', 'KWD', 0.0836, '2026-05-15', 'manual')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- approval_rules
-- ---------------------------------------------------------------------------

INSERT INTO public.approval_rules (id, company_id, doc_type, min_amount, max_amount, approver_roles, sequence, active)
VALUES
  ('ar_po_1', 'co_1', 'po', 0, NULL, ARRAY['approver']::text[], 1, true),
  ('ar_po_2', 'co_1', 'po', 5000, NULL, ARRAY['approver']::text[], 2, true),
  ('ar_po_3', 'co_1', 'po', 50000, NULL, ARRAY['admin']::text[], 3, true),
  ('ar_bill_1', 'co_1', 'vendor_bill', 0, NULL, ARRAY['approver']::text[], 1, true),
  ('ar_bill_2', 'co_1', 'vendor_bill', 10000, NULL, ARRAY['approver']::text[], 2, true),
  ('ar_vpay_1', 'co_1', 'vendor_payment', 0, NULL, ARRAY['admin']::text[], 1, true),
  ('ar_so_1', 'co_1', 'so', 0, NULL, ARRAY['approver']::text[], 1, true),
  ('ar_so_2', 'co_1', 'so', 20000, NULL, ARRAY['approver']::text[], 2, true),
  ('ar_inv_1', 'co_1', 'customer_invoice', 0, NULL, ARRAY['approver']::text[], 1, true),
  ('ar_adj_1', 'co_1', 'stock_adjustment', 0, NULL, ARRAY['approver']::text[], 1, true),
  ('ar_adj_2', 'co_1', 'stock_adjustment', 5000, NULL, ARRAY['admin']::text[], 2, true),
  ('ar_je_1', 'co_1', 'journal_entry', 0, NULL, ARRAY['approver', 'accountant']::text[], 1, true),
  ('ar_je_2', 'co_1', 'journal_entry', 50000, NULL, ARRAY['admin']::text[], 2, true)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- document_sequences
-- ---------------------------------------------------------------------------

INSERT INTO public.document_sequences (id, company_id, doc_type, prefix, year, padding, next_number)
VALUES
  ('seq_co_1_pr_2026', 'co_1', 'pr', 'PR', 2026, 5, 2),
  ('seq_co_1_rfq_2026', 'co_1', 'rfq', 'RFQ', 2026, 5, 2),
  ('seq_co_1_po_2026', 'co_1', 'po', 'PO', 2026, 5, 6),
  ('seq_co_1_grn_2026', 'co_1', 'grn', 'GRN', 2026, 5, 3),
  ('seq_co_1_vendor_bill_2026', 'co_1', 'vendor_bill', 'BILL', 2026, 5, 5),
  ('seq_co_1_vendor_payment_2026', 'co_1', 'vendor_payment', 'VPAY', 2026, 5, 2),
  ('seq_co_1_debit_note_2026', 'co_1', 'debit_note', 'DN', 2026, 5, 2),
  ('seq_co_1_vendor_return_2026', 'co_1', 'vendor_return', 'VR', 2026, 5, 2),
  ('seq_co_1_opportunity_2026', 'co_1', 'opportunity', 'OPP', 2026, 5, 3),
  ('seq_co_1_quote_2026', 'co_1', 'quote', 'QT', 2026, 5, 5),
  ('seq_co_1_so_2026', 'co_1', 'so', 'SO', 2026, 5, 3),
  ('seq_co_1_dn_2026', 'co_1', 'dn', 'DEL', 2026, 5, 2),
  ('seq_co_1_customer_invoice_2026', 'co_1', 'customer_invoice', 'INV', 2026, 5, 2),
  ('seq_co_1_customer_receipt_2026', 'co_1', 'customer_receipt', 'RCP', 2026, 5, 2),
  ('seq_co_1_credit_note_2026', 'co_1', 'credit_note', 'CN', 2026, 5, 2),
  ('seq_co_1_customer_return_2026', 'co_1', 'customer_return', 'CR', 2026, 5, 2),
  ('seq_co_1_journal_entry_2026', 'co_1', 'journal_entry', 'JE', 2026, 5, 9),
  ('seq_co_1_stock_move_2026', 'co_1', 'stock_move', 'SM', 2026, 6, 7),
  ('seq_co_1_stock_adjustment_2026', 'co_1', 'stock_adjustment', 'ADJ', 2026, 5, 2),
  ('seq_co_1_internal_transfer_2026', 'co_1', 'internal_transfer', 'TRX', 2026, 5, 2)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- purchase_requisitions + lines
-- ---------------------------------------------------------------------------

INSERT INTO public.purchase_requisitions (id, company_id, number, requested_by, date, needed_by, state, notes)
VALUES
  ('pr_1', 'co_1', 'PR-2026-00001', 'Demo User', '2026-04-10', '2026-04-20', 'posted', 'Approved by Khalid (warehouse manager).')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.purchase_requisition_lines (id, company_id, purchase_requisition_id, product_id, description, qty, unit_price, tax_code_id)
VALUES
  ('pr_1_l1', 'co_1', 'pr_1', 'prod_1', 'Resin 25kg — for Q2 production', 80, 12.4, 'tax_kw_vat_5')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- rfqs + children (award FKs filled after quotes + POs)
-- ---------------------------------------------------------------------------

INSERT INTO public.rfqs (id, company_id, number, date, expected_quote_by, state, awarded_vendor_id, awarded_quote_id, award_po_id, awarded_at, awarded_by, notes)
VALUES
  ('rfq_1', 'co_1', 'RFQ-2026-00001', '2026-04-10', '2026-04-12', 'closed', 'sup_1', NULL, NULL, '2026-04-12', 'Demo User', 'Awarded to sup_1 (best price, in-policy lead time).')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.rfq_sources (id, company_id, rfq_id, purchase_requisition_id)
VALUES
  ('rfq_1_src_1', 'co_1', 'rfq_1', 'pr_1')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.rfq_invited_suppliers (id, company_id, rfq_id, supplier_id, sent_at)
VALUES
  ('rfq_1_inv_1', 'co_1', 'rfq_1', 'sup_1', '2026-04-10T09:00:00Z'),
  ('rfq_1_inv_2', 'co_1', 'rfq_1', 'sup_2', '2026-04-10T09:00:00Z'),
  ('rfq_1_inv_3', 'co_1', 'rfq_1', 'sup_4', '2026-04-10T09:00:00Z')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.rfq_lines (id, company_id, rfq_id, product_id, description, qty)
VALUES
  ('rfq_1_l1', 'co_1', 'rfq_1', 'prod_1', 'Resin 25kg — Q2 production', 80)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.rfq_quotes (id, company_id, rfq_id, vendor_id, received_date, currency, total, valid_until)
VALUES
  ('rfq_1_q_sup_1', 'co_1', 'rfq_1', 'sup_1', '2026-04-11', 'KWD', 992, '2026-05-11'),
  ('rfq_1_q_sup_2', 'co_1', 'rfq_1', 'sup_2', '2026-04-11', 'KWD', 1032, '2026-05-11'),
  ('rfq_1_q_sup_4', 'co_1', 'rfq_1', 'sup_4', '2026-04-12', 'USD', 1056, '2026-05-12')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.rfq_quote_lines (id, company_id, rfq_quote_id, rfq_line_id, unit_price, lead_time_days, notes)
VALUES
  ('rfq_1_q_sup_1_l1', 'co_1', 'rfq_1_q_sup_1', 'rfq_1_l1', 12.4, 5, NULL),
  ('rfq_1_q_sup_2_l1', 'co_1', 'rfq_1_q_sup_2', 'rfq_1_l1', 12.9, 3, NULL),
  ('rfq_1_q_sup_4_l1', 'co_1', 'rfq_1_q_sup_4', 'rfq_1_l1', 13.2, 7, 'USD-pricing, FX risk')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- purchase_orders + lines
-- ---------------------------------------------------------------------------

INSERT INTO public.purchase_orders (id, company_id, number, supplier_id, pr_id, date, expected_date, currency, payment_term_id, warehouse_id, state, subtotal, tax_total, total, notes)
VALUES
  ('po_1', 'co_1', 'PO-2026-00001', 'sup_1', 'pr_1', '2026-04-12', '2026-04-18', 'KWD', 'pt_net30', 'wh_1', 'posted', 992, 49.6, 1041.6, NULL),
  ('po_2', 'co_1', 'PO-2026-00002', 'sup_2', NULL, '2026-04-14', '2026-04-20', 'KWD', 'pt_net30', 'wh_1', 'confirmed', 175, 8.75, 183.75, NULL),
  ('po_3', 'co_1', 'PO-2026-00003', 'sup_3', NULL, '2026-04-25', '2026-05-05', 'KWD', 'pt_net60', 'wh_1', 'draft', 350, 17.5, 367.5, NULL),
  ('po_4', 'co_1', 'PO-2026-00004', 'sup_2', NULL, '2026-02-15', '2026-02-25', 'KWD', 'pt_net30', 'wh_1', 'confirmed', 70, 3.5, 73.5, 'Legacy doc retained for period-locked banner demo.'),
  ('po_5', 'co_1', 'PO-2026-00005', 'sup_1', NULL, '2026-03-20', '2026-03-30', 'KWD', 'pt_net30', 'wh_1', 'confirmed', 496, 24.8, 520.8, 'March soft-closed period — only `period_adjust` role can post here.')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.purchase_order_lines (id, company_id, purchase_order_id, product_id, description, qty, unit_price, tax_code_id)
VALUES
  ('po_1_l1', 'co_1', 'po_1', 'prod_1', 'Resin 25kg', 80, 12.4, 'tax_kw_vat_5'),
  ('po_2_l1', 'co_1', 'po_2', 'prod_2', 'Carton large', 500, 0.35, 'tax_kw_vat_5'),
  ('po_3_l1', 'co_1', 'po_3', 'prod_3', 'Thermal label roll', 40, 8.75, 'tax_kw_vat_5'),
  ('po_4_l1', 'co_1', 'po_4', 'prod_2', 'Carton large (legacy)', 200, 0.35, 'tax_kw_vat_5'),
  ('po_5_l1', 'co_1', 'po_5', 'prod_1', 'Resin 25kg (March batch)', 40, 12.4, 'tax_kw_vat_5')
ON CONFLICT (id) DO NOTHING;
UPDATE public.rfqs
SET awarded_quote_id = 'rfq_1_q_sup_1',
    award_po_id = 'po_1'
WHERE company_id = 'co_1' AND id = 'rfq_1'
  AND awarded_quote_id IS NULL;


-- ---------------------------------------------------------------------------
-- goods_receipts + lines
-- ---------------------------------------------------------------------------

INSERT INTO public.goods_receipts (id, company_id, number, po_id, supplier_id, warehouse_id, date, state, notes)
VALUES
  ('grn_1', 'co_1', 'GRN-2026-00001', 'po_1', 'sup_1', 'wh_1', '2026-04-18', 'posted', NULL),
  ('grn_2', 'co_1', 'GRN-2026-00002', 'po_2', 'sup_2', 'wh_1', '2026-04-19', 'posted', NULL)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.goods_receipt_lines (id, company_id, goods_receipt_id, po_line_id, product_id, description, qty, unit_price, tax_code_id, qty_received)
VALUES
  ('grn_1_l1', 'co_1', 'grn_1', 'po_1_l1', 'prod_1', 'Resin 25kg', 80, 12.4, 'tax_kw_vat_5', 80),
  ('grn_2_l1', 'co_1', 'grn_2', 'po_2_l1', 'prod_2', 'Carton large', 500, 0.35, 'tax_kw_vat_5', 500)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- vendor_bills + lines
-- ---------------------------------------------------------------------------

INSERT INTO public.vendor_bills (id, company_id, number, supplier_id, po_id, grn_id, invoice_number, date, due_date, currency, state, subtotal, tax_total, total, paid, three_way_match, discrepancy_reason)
VALUES
  ('bill_1', 'co_1', 'BILL-2026-00001', 'sup_1', 'po_1', 'grn_1', 'PCG/2026/INV-447', '2026-04-19', '2026-05-19', 'KWD', 'posted', 992, 49.6, 1041.6, 1041.6, 'matched', NULL),
  ('bill_2', 'co_1', 'BILL-2026-00002', 'sup_2', 'po_2', 'grn_2', 'PL/2026/032', '2026-04-21', '2026-05-21', 'KWD', 'pending', 182, 9.1, 191.1, 0, 'discrepancy', 'Billed qty 520 exceeds received 500.'),
  ('bill_3', 'co_1', 'BILL-2026-00003', 'sup_4', NULL, NULL, 'GS/USD/2026/118', '2026-05-10', '2026-06-09', 'USD', 'draft', 1200, 60, 1260, 0, 'review', NULL)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vendor_bill_lines (id, company_id, vendor_bill_id, po_line_id, grn_line_id, product_id, description, qty, unit_price, tax_code_id)
VALUES
  ('bill_1_l1', 'co_1', 'bill_1', 'po_1_l1', 'grn_1_l1', 'prod_1', 'Resin 25kg', 80, 12.4, 'tax_kw_vat_5'),
  ('bill_2_l1', 'co_1', 'bill_2', 'po_2_l1', 'grn_2_l1', 'prod_2', 'Carton large (billed 520 vs received 500)', 520, 0.35, 'tax_kw_vat_5'),
  ('bill_3_l1', 'co_1', 'bill_3', NULL, NULL, 'prod_3', 'Imported thermal labels (USD)', 100, 12, 'tax_kw_vat_5')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- vendor_payments + allocations
-- ---------------------------------------------------------------------------

INSERT INTO public.vendor_payments (id, company_id, number, supplier_id, bank_account_id, date, currency, state, amount, method)
VALUES
  ('vpay_1', 'co_1', 'VPAY-2026-00001', 'sup_1', 'bank_1', '2026-05-15', 'KWD', 'posted', 1041.6, 'wire')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vendor_payment_allocations (id, company_id, vendor_payment_id, bill_id, amount)
VALUES
  ('vpay_1_a1', 'co_1', 'vpay_1', 'bill_1', 1041.6)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- vendor_returns + lines (debit_note_id linked after)
-- ---------------------------------------------------------------------------

INSERT INTO public.vendor_returns (id, company_id, number, grn_id, supplier_id, warehouse_id, date, state, debit_note_id, notes)
VALUES
  ('vret_1', 'co_1', 'VR-2026-00001', 'grn_2', 'sup_2', 'wh_1', '2026-04-22', 'posted', NULL, 'Partial return; remaining 480 retained.')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vendor_return_lines (id, company_id, vendor_return_id, grn_line_id, product_id, description, qty, unit_price, tax_code_id, reason_code, notes)
VALUES
  ('vret_1_l1', 'co_1', 'vret_1', 'grn_2_l1', 'prod_2', 'Carton large — water-damaged shipment subset', 20, 0.35, 'tax_kw_vat_5', 'damaged', 'Vendor confirmed via call 22 Apr.')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- debit_notes
-- ---------------------------------------------------------------------------

INSERT INTO public.debit_notes (id, company_id, number, supplier_id, vendor_return_id, bill_id, date, currency, state, subtotal, tax_total, total, settled)
VALUES
  ('dnote_1', 'co_1', 'DN-2026-00001', 'sup_2', 'vret_1', 'bill_2', '2026-04-22', 'KWD', 'posted', 7, 0.35, 7.35, 0)
ON CONFLICT (id) DO NOTHING;
UPDATE public.vendor_returns
SET debit_note_id = 'dnote_1'
WHERE company_id = 'co_1' AND id = 'vret_1' AND debit_note_id IS NULL;


-- ---------------------------------------------------------------------------
-- opportunities
-- ---------------------------------------------------------------------------

INSERT INTO public.opportunities (id, company_id, number, customer_id, title, stage, value, probability, next_action, days_idle)
VALUES
  ('opp_1', 'co_1', 'OPP-2026-00001', 'cust_1', 'POS rollout — Phase 2', 'won', 22000, 1, 'Hand off to delivery', 0),
  ('opp_2', 'co_1', 'OPP-2026-00002', 'cust_4', 'Annual supply — beverages', 'negotiation', 55000, 0.7, 'Legal review of terms', 18)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- quotes + lines
-- ---------------------------------------------------------------------------

INSERT INTO public.quotes (id, company_id, number, customer_id, opportunity_id, date, valid_until, currency, state, subtotal, tax_total, total, notes)
VALUES
  ('qt_1', 'co_1', 'QT-2026-00001', 'cust_1', 'opp_1', '2026-04-05', '2026-05-05', 'KWD', 'accepted', 1780, 89, 1869, NULL),
  ('qt_2', 'co_1', 'QT-2026-00002', 'cust_2', NULL, '2026-04-22', '2026-05-22', 'KWD', 'draft', 212.5, 10.625, 223.125, NULL),
  ('qt_3', 'co_1', 'QT-2026-00003', 'cust_4', 'opp_2', '2026-04-15', '2026-05-15', 'KWD', 'accepted', 8700, 435, 9135, NULL),
  ('qt_4', 'co_1', 'QT-2026-00004', 'cust_3', NULL, '2026-03-01', '2026-04-01', 'KWD', 'expired', 425, 21.25, 446.25, NULL)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.quote_lines (id, company_id, quote_id, product_id, description, qty, unit_price, tax_code_id)
VALUES
  ('qt_1_l1', 'co_1', 'qt_1', 'prod_4', 'Display cooler — 2 door', 2, 890, 'tax_kw_vat_5'),
  ('qt_2_l1', 'co_1', 'qt_2', 'prod_5', 'Barcode scanner kit', 5, 42.5, 'tax_kw_vat_5'),
  ('qt_3_l1', 'co_1', 'qt_3', 'prod_4', 'Display cooler — 2 door (annual supply, year 1)', 10, 870, 'tax_kw_vat_5'),
  ('qt_4_l1', 'co_1', 'qt_4', 'prod_5', 'Barcode scanner kit (expired)', 10, 42.5, 'tax_kw_vat_5')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- sales_orders + lines
-- ---------------------------------------------------------------------------

INSERT INTO public.sales_orders (id, company_id, number, customer_id, quote_id, date, expected_delivery_date, currency, warehouse_id, state, blocked_reason, exceptional, subtotal, tax_total, total)
VALUES
  ('so_1', 'co_1', 'SO-2026-00001', 'cust_1', 'qt_1', '2026-04-08', '2026-04-14', 'KWD', 'wh_2', 'posted', NULL, false, 1780, 89, 1869),
  ('so_2', 'co_1', 'SO-2026-00002', 'cust_4', 'qt_3', '2026-04-16', '2026-04-25', 'KWD', 'wh_1', 'draft', 'Customer on credit hold (exposure 62,500 > limit 60,000)', true, 8700, 435, 9135)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.sales_order_lines (id, company_id, sales_order_id, product_id, description, qty, unit_price, tax_code_id)
VALUES
  ('so_1_l1', 'co_1', 'so_1', 'prod_4', 'Display cooler — 2 door', 2, 890, 'tax_kw_vat_5'),
  ('so_2_l1', 'co_1', 'so_2', 'prod_4', 'Display cooler — 2 door (annual supply, year 1)', 10, 870, 'tax_kw_vat_5')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- delivery_notes + lines
-- ---------------------------------------------------------------------------

INSERT INTO public.delivery_notes (id, company_id, number, so_id, customer_id, warehouse_id, date, state)
VALUES
  ('dn_1', 'co_1', 'DEL-2026-00001', 'so_1', 'cust_1', 'wh_2', '2026-04-12', 'posted')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.delivery_note_lines (id, company_id, delivery_note_id, so_line_id, product_id, description, qty, unit_price, tax_code_id, qty_delivered)
VALUES
  ('dn_1_l1', 'co_1', 'dn_1', 'so_1_l1', 'prod_4', 'Display cooler — 2 door (lot DC-2026-Q2)', 2, 890, 'tax_kw_vat_5', 2)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- customer_invoices + lines
-- ---------------------------------------------------------------------------

INSERT INTO public.customer_invoices (id, company_id, number, customer_id, so_id, dn_id, date, due_date, currency, state, subtotal, tax_total, total, paid)
VALUES
  ('inv_1', 'co_1', 'INV-2026-00001', 'cust_1', 'so_1', 'dn_1', '2026-04-13', '2026-05-13', 'KWD', 'posted', 1780, 89, 1869, 1869)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.customer_invoice_lines (id, company_id, customer_invoice_id, so_line_id, dn_line_id, product_id, description, qty, unit_price, tax_code_id)
VALUES
  ('inv_1_l1', 'co_1', 'inv_1', 'so_1_l1', 'dn_1_l1', 'prod_4', 'Display cooler — 2 door', 2, 890, 'tax_kw_vat_5')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- customer_receipts + allocations
-- ---------------------------------------------------------------------------

INSERT INTO public.customer_receipts (id, company_id, number, customer_id, bank_account_id, date, currency, state, amount, method)
VALUES
  ('rcp_1', 'co_1', 'RCP-2026-00001', 'cust_1', 'bank_1', '2026-05-02', 'KWD', 'posted', 1869, 'wire')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.customer_receipt_allocations (id, company_id, customer_receipt_id, invoice_id, amount)
VALUES
  ('rcp_1_a1', 'co_1', 'rcp_1', 'inv_1', 1869)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- customer_returns + lines (credit_note_id linked after)
-- ---------------------------------------------------------------------------

INSERT INTO public.customer_returns (id, company_id, number, dn_id, customer_id, warehouse_id, date, state, credit_note_id, notes)
VALUES
  ('cret_1', 'co_1', 'CR-2026-00001', 'dn_1', 'cust_1', 'wh_2', '2026-04-22', 'posted', NULL, 'Customer reported door seal defect on one unit.')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.customer_return_lines (id, company_id, customer_return_id, dn_line_id, product_id, description, qty, unit_price, tax_code_id, reason_code, lot_number)
VALUES
  ('cret_1_l1', 'co_1', 'cret_1', 'dn_1_l1', 'prod_4', 'Display cooler — door seal defect', 1, 890, 'tax_kw_vat_5', 'damaged', 'DC-2026-Q2')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- credit_notes
-- ---------------------------------------------------------------------------

INSERT INTO public.credit_notes (id, company_id, number, customer_id, customer_return_id, invoice_id, date, currency, state, subtotal, tax_total, total, applied)
VALUES
  ('cnote_1', 'co_1', 'CN-2026-00001', 'cust_1', 'cret_1', 'inv_1', '2026-04-22', 'KWD', 'posted', 890, 44.5, 934.5, 0)
ON CONFLICT (id) DO NOTHING;
UPDATE public.customer_returns
SET credit_note_id = 'cnote_1'
WHERE company_id = 'co_1' AND id = 'cret_1' AND credit_note_id IS NULL;


-- ---------------------------------------------------------------------------
-- journal_entries + lines
-- ---------------------------------------------------------------------------

INSERT INTO public.journal_entries (id, company_id, number, date, currency, state, source_type, source_id, description)
VALUES
  ('je_grn_1', 'co_1', 'JE-2026-00001', '2026-04-18', 'KWD', 'posted', 'grn', 'grn_1', 'Goods received — PetroChem Gulf · Resin 25kg × 80'),
  ('je_grn_2', 'co_1', 'JE-2026-00002', '2026-04-19', 'KWD', 'posted', 'grn', 'grn_2', 'Goods received — PackLine KW · Carton × 500'),
  ('je_bill_1', 'co_1', 'JE-2026-00003', '2026-04-19', 'KWD', 'posted', 'vendor_bill', 'bill_1', 'Vendor bill — PetroChem Gulf · BILL-2026-00001'),
  ('je_vpay_1', 'co_1', 'JE-2026-00004', '2026-05-15', 'KWD', 'posted', 'vendor_payment', 'vpay_1', 'Vendor payment — PetroChem Gulf · VPAY-2026-00001'),
  ('je_dn_1', 'co_1', 'JE-2026-00005', '2026-04-12', 'KWD', 'posted', 'dn', 'dn_1', 'Delivery — Kuwait Retail Co. · Display cooler × 2'),
  ('je_inv_1', 'co_1', 'JE-2026-00006', '2026-04-13', 'KWD', 'posted', 'customer_invoice', 'inv_1', 'Customer invoice — Kuwait Retail Co. · INV-2026-00001'),
  ('je_rcp_1', 'co_1', 'JE-2026-00007', '2026-05-02', 'KWD', 'posted', 'customer_receipt', 'rcp_1', 'Customer receipt — Kuwait Retail Co. · RCP-2026-00001'),
  ('je_adj_1', 'co_1', 'JE-2026-00008', '2026-04-20', 'KWD', 'posted', 'stock_adjustment', 'adj_1', 'Stock adjustment — Thermal labels × -6 (damage)')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.journal_entry_lines (id, company_id, journal_entry_id, account_id, description, debit, credit)
VALUES
  ('je_grn_1_l1', 'co_1', 'je_grn_1', 'acc_inv', 'Inventory in', 992, 0),
  ('je_grn_1_l2', 'co_1', 'je_grn_1', 'acc_grir', 'GR/IR clearing', 0, 992),
  ('je_grn_2_l1', 'co_1', 'je_grn_2', 'acc_inv', 'Inventory in', 175, 0),
  ('je_grn_2_l2', 'co_1', 'je_grn_2', 'acc_grir', 'GR/IR clearing', 0, 175),
  ('je_bill_1_l1', 'co_1', 'je_bill_1', 'acc_grir', 'GR/IR clearing', 992, 0),
  ('je_bill_1_l2', 'co_1', 'je_bill_1', 'acc_input_vat', 'Input VAT 5%', 49.6, 0),
  ('je_bill_1_l3', 'co_1', 'je_bill_1', 'acc_ap', 'AP — PetroChem Gulf', 0, 1041.6),
  ('je_vpay_1_l1', 'co_1', 'je_vpay_1', 'acc_ap', 'AP settled', 1041.6, 0),
  ('je_vpay_1_l2', 'co_1', 'je_vpay_1', 'acc_bank_nbk_kwd', 'Bank out', 0, 1041.6),
  ('je_dn_1_l1', 'co_1', 'je_dn_1', 'acc_cogs', 'COGS', 1240, 0),
  ('je_dn_1_l2', 'co_1', 'je_dn_1', 'acc_inv', 'Inventory out', 0, 1240),
  ('je_inv_1_l1', 'co_1', 'je_inv_1', 'acc_ar', 'AR — Kuwait Retail', 1869, 0),
  ('je_inv_1_l2', 'co_1', 'je_inv_1', 'acc_revenue', 'Revenue', 0, 1780),
  ('je_inv_1_l3', 'co_1', 'je_inv_1', 'acc_output_vat', 'Output VAT 5%', 0, 89),
  ('je_rcp_1_l1', 'co_1', 'je_rcp_1', 'acc_bank_nbk_kwd', 'Bank in', 1869, 0),
  ('je_rcp_1_l2', 'co_1', 'je_rcp_1', 'acc_ar', 'AR settled', 0, 1869),
  ('je_adj_1_l1', 'co_1', 'je_adj_1', 'acc_inv_loss', 'Inventory loss', 52.5, 0),
  ('je_adj_1_l2', 'co_1', 'je_adj_1', 'acc_inv', 'Inventory write-down', 0, 52.5)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- internal_transfers + lines
-- ---------------------------------------------------------------------------

INSERT INTO public.internal_transfers (id, company_id, number, from_warehouse_id, to_warehouse_id, date, state, notes)
VALUES
  ('trx_1', 'co_1', 'TRX-2026-00001', 'wh_1', 'wh_2', '2026-04-09', 'posted', 'Showroom restock ahead of Kuwait Retail delivery.')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.internal_transfer_lines (id, company_id, internal_transfer_id, product_id, qty, lot_number)
VALUES
  ('trx_1_l1', 'co_1', 'trx_1', 'prod_4', 4, 'DC-2026-Q2')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- stock_adjustments + lines
-- ---------------------------------------------------------------------------

INSERT INTO public.stock_adjustments (id, company_id, number, date, state, approved_by, notes)
VALUES
  ('adj_1', 'co_1', 'ADJ-2026-00001', '2026-04-20', 'posted', 'Demo User', 'Water damage during April rain.')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.stock_adjustment_lines (id, company_id, stock_adjustment_id, product_id, warehouse_id, qty_delta, reason)
VALUES
  ('adj_1_l1', 'co_1', 'adj_1', 'prod_3', 'wh_1', -6, 'damage')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- stock_moves
-- ---------------------------------------------------------------------------

INSERT INTO public.stock_moves (id, company_id, number, date, product_id, warehouse_id, direction, qty, cost_per_unit, lot_number, source_type, source_id)
VALUES
  ('sm_1', 'co_1', 'SM-000001', '2026-04-18', 'prod_1', 'wh_1', 'in', 80, 12.4, NULL, 'grn', 'grn_1'),
  ('sm_2', 'co_1', 'SM-000002', '2026-04-19', 'prod_2', 'wh_1', 'in', 500, 0.35, NULL, 'grn', 'grn_2'),
  ('sm_3', 'co_1', 'SM-000003', '2026-04-12', 'prod_4', 'wh_2', 'out', 2, 620, 'DC-2026-Q2', 'delivery_note', 'dn_1'),
  ('sm_4', 'co_1', 'SM-000004', '2026-04-09', 'prod_4', 'wh_1', 'out', 4, 620, NULL, 'internal_transfer', 'trx_1'),
  ('sm_5', 'co_1', 'SM-000005', '2026-04-10', 'prod_4', 'wh_2', 'in', 4, 620, NULL, 'internal_transfer', 'trx_1'),
  ('sm_6', 'co_1', 'SM-000006', '2026-04-20', 'prod_3', 'wh_1', 'out', 6, 8.75, NULL, 'stock_adjustment', 'adj_1')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- inventory_lots (mock lot DC-2026-Q2 only)
-- ---------------------------------------------------------------------------

INSERT INTO public.inventory_lots (id, company_id, product_id, warehouse_id, lot_number, received_on, on_hand, status)
VALUES
  ('lot_dc_2026_q2_wh1', 'co_1', 'prod_4', 'wh_1', 'DC-2026-Q2', '2026-04-01', 0, 'depleted'),
  ('lot_dc_2026_q2_wh2', 'co_1', 'prod_4', 'wh_2', 'DC-2026-Q2', '2026-04-10', 3, 'active')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- audit_events ("by" left NULL — no fake auth.users)
-- ---------------------------------------------------------------------------

INSERT INTO public.audit_events (id, company_id, doc_id, doc_type, from_state, to_state, "by", reason, at)
VALUES
  ('ae_1', 'co_1', 'pr_1', 'pr', NULL, 'draft', NULL, NULL, '2026-04-10T08:30:00Z'),
  ('ae_2', 'co_1', 'pr_1', 'pr', 'draft', 'pending', NULL, NULL, '2026-04-10T09:00:00Z'),
  ('ae_3', 'co_1', 'pr_1', 'pr', 'pending', 'confirmed', NULL, 'Approved.', '2026-04-10T11:20:00Z'),
  ('ae_4', 'co_1', 'pr_1', 'pr', 'confirmed', 'posted', NULL, 'PO-2026-00001 raised.', '2026-04-12T07:00:00Z'),
  ('ae_10', 'co_1', 'po_1', 'po', NULL, 'draft', NULL, NULL, '2026-04-12T08:00:00Z'),
  ('ae_11', 'co_1', 'po_1', 'po', 'draft', 'pending', NULL, NULL, '2026-04-12T08:20:00Z'),
  ('ae_12', 'co_1', 'po_1', 'po', 'pending', 'confirmed', NULL, NULL, '2026-04-12T10:10:00Z'),
  ('ae_13', 'co_1', 'po_1', 'po', 'confirmed', 'posted', NULL, 'Closed (fully received + invoiced + paid).', '2026-04-19T16:00:00Z'),
  ('ae_14', 'co_1', 'po_2', 'po', NULL, 'draft', NULL, NULL, '2026-04-14T09:00:00Z'),
  ('ae_15', 'co_1', 'po_2', 'po', 'draft', 'confirmed', NULL, NULL, '2026-04-14T10:00:00Z'),
  ('ae_16', 'co_1', 'po_3', 'po', NULL, 'draft', NULL, NULL, '2026-04-25T13:00:00Z'),
  ('ae_20', 'co_1', 'grn_1', 'grn', NULL, 'draft', NULL, NULL, '2026-04-18T07:00:00Z'),
  ('ae_21', 'co_1', 'grn_1', 'grn', 'draft', 'posted', NULL, NULL, '2026-04-18T07:30:00Z'),
  ('ae_22', 'co_1', 'grn_2', 'grn', NULL, 'draft', NULL, NULL, '2026-04-19T09:00:00Z'),
  ('ae_23', 'co_1', 'grn_2', 'grn', 'draft', 'posted', NULL, NULL, '2026-04-19T09:30:00Z'),
  ('ae_30', 'co_1', 'bill_1', 'vendor_bill', NULL, 'draft', NULL, NULL, '2026-04-19T11:00:00Z'),
  ('ae_31', 'co_1', 'bill_1', 'vendor_bill', 'draft', 'pending', NULL, NULL, '2026-04-19T11:10:00Z'),
  ('ae_32', 'co_1', 'bill_1', 'vendor_bill', 'pending', 'confirmed', NULL, '3-way match OK.', '2026-04-19T12:00:00Z'),
  ('ae_33', 'co_1', 'bill_1', 'vendor_bill', 'confirmed', 'posted', NULL, NULL, '2026-04-19T14:30:00Z'),
  ('ae_34', 'co_1', 'bill_2', 'vendor_bill', NULL, 'draft', NULL, NULL, '2026-04-21T09:00:00Z'),
  ('ae_35', 'co_1', 'bill_2', 'vendor_bill', 'draft', 'pending', NULL, 'Billed 520 vs received 500 — awaiting approver.', '2026-04-21T09:30:00Z'),
  ('ae_40', 'co_1', 'vpay_1', 'vendor_payment', NULL, 'draft', NULL, NULL, '2026-05-15T10:00:00Z'),
  ('ae_41', 'co_1', 'vpay_1', 'vendor_payment', 'draft', 'posted', NULL, NULL, '2026-05-15T10:30:00Z'),
  ('ae_50', 'co_1', 'opp_1', 'opportunity', NULL, 'confirmed', NULL, 'Stage: won.', '2026-04-01T10:00:00Z'),
  ('ae_51', 'co_1', 'qt_1', 'quote', NULL, 'draft', NULL, NULL, '2026-04-05T08:00:00Z'),
  ('ae_52', 'co_1', 'qt_1', 'quote', 'draft', 'posted', NULL, 'Sent to customer.', '2026-04-05T09:00:00Z'),
  ('ae_53', 'co_1', 'qt_1', 'quote', 'posted', 'confirmed', NULL, 'Accepted.', '2026-04-07T13:00:00Z'),
  ('ae_60', 'co_1', 'so_1', 'so', NULL, 'draft', NULL, NULL, '2026-04-08T08:00:00Z'),
  ('ae_61', 'co_1', 'so_1', 'so', 'draft', 'confirmed', NULL, NULL, '2026-04-08T09:00:00Z'),
  ('ae_62', 'co_1', 'so_1', 'so', 'confirmed', 'posted', NULL, 'Closed (delivered + invoiced + paid).', '2026-04-13T14:00:00Z'),
  ('ae_63', 'co_1', 'so_2', 'so', NULL, 'draft', NULL, 'Confirm blocked — customer on credit hold.', '2026-04-16T11:00:00Z'),
  ('ae_70', 'co_1', 'dn_1', 'dn', NULL, 'draft', NULL, NULL, '2026-04-12T08:30:00Z'),
  ('ae_71', 'co_1', 'dn_1', 'dn', 'draft', 'posted', NULL, NULL, '2026-04-12T09:00:00Z'),
  ('ae_80', 'co_1', 'inv_1', 'customer_invoice', NULL, 'draft', NULL, NULL, '2026-04-13T10:00:00Z'),
  ('ae_81', 'co_1', 'inv_1', 'customer_invoice', 'draft', 'posted', NULL, NULL, '2026-04-13T11:00:00Z'),
  ('ae_90', 'co_1', 'rcp_1', 'customer_receipt', NULL, 'draft', NULL, NULL, '2026-05-02T09:00:00Z'),
  ('ae_91', 'co_1', 'rcp_1', 'customer_receipt', 'draft', 'posted', NULL, NULL, '2026-05-02T09:15:00Z'),
  ('ae_100', 'co_1', 'trx_1', 'internal_transfer', NULL, 'posted', NULL, NULL, '2026-04-09T16:00:00Z'),
  ('ae_101', 'co_1', 'adj_1', 'stock_adjustment', NULL, 'pending', NULL, 'Damage — flagged for approval.', '2026-04-20T08:00:00Z'),
  ('ae_102', 'co_1', 'adj_1', 'stock_adjustment', 'pending', 'posted', NULL, NULL, '2026-04-20T08:30:00Z')
ON CONFLICT (id) DO NOTHING;
-- Explicitly skipped (auth / not in co_1 mock seed):
--   other demo companies and their branches
--   non-KW tax codes from the mock catalog
--   bill_4 / bill_4_l1 — blocked by UNIQUE (company_id, supplier_id, invoice_number)
--     (mock intentionally duplicates bill_1 vendor invoice number)
--   approval_requests, approval_steps, approval_decisions, notifications
--   user_profiles, company_members, invitations
--   price_lists, bank statements / reconciliation, period_close_*, fixed_assets
--   document_links (not present in mocks)
--   account_mappings: cash, wht_payable, retained_earnings, depreciation_expense,
--     accumulated_depreciation (no matching mock accounts)
