import type {
  CreditNote,
  CustomerReturn,
  DebitNote,
  VendorReturn,
} from "@/types";

/**
 * Seeded reverse-flow docs:
 *   VR-2026-00001 — GRN-2026-00002 partial return (vendor sent damaged cartons)
 *   DN-2026-00001 — Debit Note generated by the return, applied against BILL-2026-00002
 *   CR-2026-00001 — DEL-2026-00001 partial customer return (1 of 2 coolers came back)
 *   CN-2026-00001 — Credit Note generated by the customer return, applied against INV-2026-00001
 */

export const VENDOR_RETURNS: VendorReturn[] = [
  {
    id: "vret_1",
    rowVersion: 1,
    number: "VR-2026-00001",
    companyId: "co_1",
    grnId: "grn_2",
    supplierId: "sup_2",
    warehouseId: "wh_1",
    date: "2026-04-22",
    state: "posted",
    debitNoteId: "dnote_1",
    lines: [
      {
        id: "vret_1_l1",
        grnLineId: "grn_2_l1",
        productId: "prod_2",
        description: "Carton large — water-damaged shipment subset",
        qty: 20,
        unitPrice: 0.35,
        taxCodeId: "tax_kw_vat_5",
        reasonCode: "damaged",
        notes: "Vendor confirmed via call 22 Apr.",
      },
    ],
    notes: "Partial return; remaining 480 retained.",
  },
];

export const DEBIT_NOTES: DebitNote[] = [
  {
    id: "dnote_1",
    rowVersion: 1,
    number: "DN-2026-00001",
    companyId: "co_1",
    supplierId: "sup_2",
    vendorReturnId: "vret_1",
    billId: "bill_2",
    date: "2026-04-22",
    currency: "KWD",
    state: "posted",
    subtotal: 7,
    taxTotal: 0.35,
    total: 7.35,
    settled: 0,
  },
];

export const CUSTOMER_RETURNS: CustomerReturn[] = [
  {
    id: "cret_1",
    rowVersion: 1,
    number: "CR-2026-00001",
    companyId: "co_1",
    dnId: "dn_1",
    customerId: "cust_1",
    warehouseId: "wh_2",
    date: "2026-04-22",
    state: "posted",
    creditNoteId: "cnote_1",
    lines: [
      {
        id: "cret_1_l1",
        dnLineId: "dn_1_l1",
        productId: "prod_4",
        description: "Display cooler — door seal defect",
        qty: 1,
        unitPrice: 890,
        taxCodeId: "tax_kw_vat_5",
        reasonCode: "damaged",
        lotNumber: "DC-2026-Q2",
      },
    ],
    notes: "Customer reported door seal defect on one unit.",
  },
];

export const CREDIT_NOTES: CreditNote[] = [
  {
    id: "cnote_1",
    rowVersion: 1,
    number: "CN-2026-00001",
    companyId: "co_1",
    customerId: "cust_1",
    customerReturnId: "cret_1",
    invoiceId: "inv_1",
    date: "2026-04-22",
    currency: "KWD",
    state: "posted",
    subtotal: 890,
    taxTotal: 44.5,
    total: 934.5,
    applied: 0,
  },
];
