// pdf-gen edge function — single-file (InsForge `--file` does not bundle local imports).
// Black/white only (per InvoiceQuickly print best practices + Ahmad).
// Arabic RTL (per Invovate): flip entire page structure, Western numerals stay Latin.
// PDF/A-2b archival (per research). pdfnative block-based API (no JSX, no pdfnative-react).

import {
  buildDocumentPDFBytes,
  registerFonts,
  loadFontData,
  type DocumentBlock,
  type FontEntry,
  type PdfLayoutOptions,
} from 'npm:pdfnative';
import { createClient } from 'npm:@insforge/sdk';

// ─── types ────────────────────────────────────────────────────────────────

type DocType =
  | 'quote'
  | 'invoice'
  | 'delivery'
  | 'purchase_order'
  | 'vendor_bill'
  | 'financial';

type FinancialType = 'pl' | 'balance_sheet' | 'cash_flow' | 'trial_balance';
type PdfLocale = 'en' | 'ar';
type PdfMode = 'preview' | 'save';

type DocInput = {
  docType: DocType;
  docId: string;
  locale: PdfLocale;
  mode: PdfMode;
};

type FinancialInput = {
  docType: 'financial';
  type: FinancialType;
  periodId: string;
  locale: PdfLocale;
  mode: PdfMode;
};

type PdfRequest = DocInput | FinancialInput;

type PdfPreviewResponse = {
  mode: 'preview';
  contentType: 'application/pdf';
  bytes: Uint8Array;
};

type PdfSaveResponse = {
  mode: 'save';
  attachmentId: string;
  url: string;
  key: string;
};

type PdfResponse = PdfPreviewResponse | PdfSaveResponse;

type LineRow = {
  code: string;
  description: string;
  qty: number | string;
  unitPrice: number | string;
  total: number | string;
};

type DocData = {
  number: string;
  date: string;
  dueDate?: string;
  validUntil?: string;
  partyType: 'customer' | 'supplier';
  partyName: string;
  partyVat?: string;
  companyName: string;
  companyVat?: string;
  currency: string;
  lines: LineRow[];
  subtotal: number;
  taxTotal: number;
  total: number;
  notes?: string;
  state: string;
};

type FinancialData = {
  statementType: string;
  period: string;
  currency: string;
  lineItems: { label: string; amount: number }[];
  totals: Record<string, number>;
};

// ─── labels (inline; generated from messages/{en,ar}.json in full build) ──────────

type Labels = {
  docType: string;
  number: string;
  date: string;
  dueDate: string;
  validUntil: string;
  customer: string;
  supplier: string;
  currency: string;
  colCode: string;
  colDescription: string;
  colQty: string;
  colUnitPrice: string;
  colTotal: string;
  subtotal: string;
  tax: string;
  total: string;
  footer: string;
  period: string;
  label: string;
  amount: string;
};

const EN: Labels = {
  docType: 'Quote',
  number: 'Number',
  date: 'Date',
  dueDate: 'Due date',
  validUntil: 'Valid until',
  customer: 'Customer',
  supplier: 'Supplier',
  currency: 'Currency',
  colCode: 'Code',
  colDescription: 'Description',
  colQty: 'Qty',
  colUnitPrice: 'Unit price',
  colTotal: 'Total',
  subtotal: 'Subtotal',
  tax: 'Tax',
  total: 'Total',
  footer: 'Generated by Atmata ERP',
  period: 'Period',
  label: 'Label',
  amount: 'Amount',
};

const AR: Labels = {
  docType: 'عرض سعر',
  number: 'الرقم',
  date: 'التاريخ',
  dueDate: 'تاريخ الاستحقاق',
  validUntil: 'صالح حتى',
  customer: 'العميل',
  supplier: 'المورد',
  currency: 'العملة',
  colCode: 'الرمز',
  colDescription: 'الوصف',
  colQty: 'الكمية',
  colUnitPrice: 'سعر الوحدة',
  colTotal: 'الإجمالي',
  subtotal: 'المجموع الفرعي',
  tax: 'الضريبة',
  total: 'الإجمالي',
  footer: 'تم إنشاؤه بواسطة Atmata ERP',
  period: 'الفترة',
  label: 'البند',
  amount: 'المبلغ',
};

function labelsFor(locale: PdfLocale): Labels {
  return locale === 'ar' ? AR : EN;
}

function docTypeLabel(docType: string, locale: PdfLocale): string {
  const map: Record<string, string> = {
    quote: labelsFor(locale).docType,
    invoice: locale === 'ar' ? 'فاتورة' : 'Invoice',
    delivery: locale === 'ar' ? 'إشعار تسليم' : 'Delivery note',
    purchase_order: locale === 'ar' ? 'أمر شراء' : 'Purchase order',
    vendor_bill: locale === 'ar' ? 'فاتورة المورد' : 'Vendor bill',
    financial: locale === 'ar' ? 'القوائم المالية' : 'Financial statement',
  };
  return map[docType] ?? labelsFor(locale).docType;
}

// ─── fonts (lazy per-locale) ──────────────────────────────────────────────

let fontsRegistered = false;

function ensureFontsRegistered(): void {
  if (fontsRegistered) return;
  registerFonts({
    ar: () => import('npm:pdfnative/fonts/noto-arabic-data.js'),
    latin: () => import('npm:pdfnative/fonts/noto-sans-data.js'),
  });
  fontsRegistered = true;
}

async function loadLocaleFonts(locale: PdfLocale): Promise<FontEntry[]> {
  ensureFontsRegistered();
  const latin = await loadFontData('latin');
  if (!latin) throw new Error('latin font failed to load');
  if (locale === 'en') return [{ fontData: latin, fontRef: 'F1', lang: 'latin' }];
  const ar = await loadFontData('ar');
  if (!ar) throw new Error('arabic font failed to load');
  return [
    { fontData: ar, fontRef: 'F2', lang: 'ar' },
    { fontData: latin, fontRef: 'F1', lang: 'latin' },
  ];
}

// ─── templates (block-based, black/white only) ───────────────────────────

const BW = {
  black: '#000000' as const,
  gray: '#666666' as const,
  lightBorder: '#CCCCCC' as const,
  altRow: '#F5F5F5' as const,
  white: '#FFFFFF' as const,
};

function lineItemsTable(lines: LineRow[], L: Labels, isAr: boolean): DocumentBlock {
  const headers = isAr
    ? [L.colCode, L.colDescription, L.colQty, L.colUnitPrice, L.colTotal]
    : ['Code', 'Description', 'Qty', 'Unit price', 'Total'];
  return {
    type: 'table',
    headers,
    rows: lines.map((l) => ({
      cells: [l.code, l.description, String(l.qty), String(l.unitPrice), String(l.total)],
    })),
    columns: [
      { f: 0.12, a: 'l' },
      { f: 0.40, a: 'l' },
      { f: 0.12, a: isAr ? 'r' : 'c' },
      { f: 0.18, a: 'r' },
      { f: 0.18, a: 'r' },
    ],
  };
}

function partyBlock(data: DocData, L: Labels, isAr: boolean): DocumentBlock {
  const partyLabel = data.partyType === 'supplier' ? L.supplier : L.customer;
  const dateLabel = data.dueDate ? L.dueDate : L.validUntil;
  const dateValue = data.dueDate ?? data.validUntil ?? data.date;
  const lines = [
    `${partyLabel}: ${data.partyName}`,
    data.partyVat ? `${L.currency}: ${data.currency}` : '',
    `${L.number}: ${data.number}`,
    `${L.date}: ${data.date}`,
    dateValue ? `${dateLabel}: ${dateValue}` : '',
  ].filter(Boolean);
  return {
    type: 'paragraph',
    text: lines.join('  ·  '),
    align: isAr ? 'right' : 'left',
    color: BW.gray,
  };
}

function totalsBlock(data: DocData, L: Labels, isAr: boolean): DocumentBlock {
  return {
    type: 'paragraph',
    text: [
      `${L.subtotal}: ${data.currency} ${data.subtotal}`,
      `${L.tax}: ${data.currency} ${data.taxTotal}`,
      `${L.total}: ${data.currency} ${data.total}`,
    ].join('  ·  '),
    align: isAr ? 'right' : 'left',
    color: BW.black,
  };
}

function buildDocBlocks(
  docType: string,
  data: DocData,
  L: Labels,
  locale: PdfLocale,
): DocumentBlock[] {
  const isAr = locale === 'ar';
  const title = `${docTypeLabel(docType, locale)} ${data.number}`;
  const blocks: DocumentBlock[] = [
    { type: 'heading', text: title, level: 1, color: BW.black },
    partyBlock(data, L, isAr),
    { type: 'spacer', height: 12 },
    lineItemsTable(data.lines, L, isAr),
    { type: 'spacer', height: 12 },
    totalsBlock(data, L, isAr),
  ];
  if (data.notes) blocks.push({ type: 'paragraph', text: data.notes, color: BW.gray });
  blocks.push({ type: 'paragraph', text: L.footer, color: BW.gray });
  return blocks;
}

function buildFinancialBlocks(
  data: FinancialData,
  L: Labels,
  locale: PdfLocale,
): DocumentBlock[] {
  const isAr = locale === 'ar';
  const blocks: DocumentBlock[] = [
    { type: 'heading', text: `${data.statementType} — ${data.period}`, level: 1, color: BW.black },
    {
      type: 'paragraph',
      text: `${L.currency}: ${data.currency}`,
      align: isAr ? 'right' : 'left',
      color: BW.gray,
    },
    { type: 'spacer', height: 12 },
    {
      type: 'table',
      headers: isAr ? [L.label, L.amount] : ['Label', 'Amount'],
      rows: data.lineItems.map((li) => ({ cells: [li.label, String(li.amount)] })),
      columns: [
        { f: 0.6, a: 'l' },
        { f: 0.4, a: 'r' },
      ],
    },
    { type: 'spacer', height: 12 },
    {
      type: 'paragraph',
      text: Object.entries(data.totals)
        .map(([k, v]) => `${k}: ${data.currency} ${v}`)
        .join('  ·  '),
      align: isAr ? 'right' : 'left',
      color: BW.black,
    },
    { type: 'paragraph', text: L.footer, color: BW.gray },
  ];
  return blocks;
}

// ─── render (B/W colors, PDF/A-2b, RTL for ar) ────────────────────────────

const TEMPLATE_VERSION = 'v1'; // scripts/pdf-template-version.mjs computes sha256 per template in full build.

const BW_COLORS = {
  title: BW.black,
  credit: BW.black,
  debit: BW.black,
  text: BW.black,
  thBg: BW.white,
  thBrd: BW.black,
  rowBrd: BW.lightBorder,
  ptdBg: BW.white,
  balBg: BW.altRow,
  balBrd: BW.black,
  label: BW.gray,
  footer: BW.gray,
};

function pageHeader(title: string, companyName: string, isAr: boolean) {
  return {
    left: isAr ? '' : companyName,
    center: '',
    right: isAr ? companyName : title,
  };
}

function pageFooter(footerText: string) {
  return { left: footerText, right: 'Page {page} of {pages}' };
}

async function renderDoc(docType: string, data: DocData, locale: PdfLocale): Promise<Uint8Array> {
  const L = labelsFor(locale);
  const isAr = locale === 'ar';
  const title = `${docTypeLabel(docType, locale)} ${data.number}`;
  const blocks = buildDocBlocks(docType, data, L, locale);
  const fontEntries = await loadLocaleFonts(locale);
  const layout: Partial<PdfLayoutOptions> = {
    direction: isAr ? 'r2l' : 'l2r',
    tagged: 'pdfa2b',
    colors: BW_COLORS,
    headerTemplate: pageHeader(title, data.companyName, isAr),
    footerTemplate: pageFooter(L.footer),
  };
  return buildDocumentPDFBytes(
    { docTitle: title, title, blocks, footerText: L.footer, fontEntries },
    layout,
  );
}

async function renderFinancial(data: FinancialData, locale: PdfLocale): Promise<Uint8Array> {
  const L = labelsFor(locale);
  const isAr = locale === 'ar';
  const title = `${data.statementType} — ${data.period}`;
  const blocks = buildFinancialBlocks(data, L, locale);
  const fontEntries = await loadLocaleFonts(locale);
  const layout: Partial<PdfLayoutOptions> = {
    direction: isAr ? 'r2l' : 'l2r',
    tagged: 'pdfa2b',
    colors: BW_COLORS,
    headerTemplate: pageHeader(title, data.companyName, isAr),
    footerTemplate: pageFooter(L.footer),
  };
  return buildDocumentPDFBytes(
    { docTitle: title, title, blocks, footerText: L.footer, fontEntries },
    layout,
  );
}

// ─── data fetch (RLS-scoped via user token) ───────────────────────────────

type SdkClient = ReturnType<typeof createClient>;

function camelize<T = Record<string, unknown>>(row: T): T {
  const out: Record<string, unknown> = {};
  for (const k of Object.keys(row)) {
    const camel = k.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
    out[camel] = row[k];
  }
  return out as T;
}

async function fetchOne<T = Record<string, unknown>>(
  c: SdkClient,
  table: string,
  id: string,
  select: string,
): Promise<T> {
  const { data, error } = await c.database
    .from(table)
    .select(select)
    .eq('id', id)
    .single();
  if (error || !data) throw new Error(`${table} fetch failed: ${error?.message ?? 'no row'}`);
  return camelize(data as T);
}

async function fetchLines(
  c: SdkClient,
  lineTable: string,
  parentCol: string,
  docId: string,
): Promise<LineRow[]> {
  const { data, error } = await c.database
    .from(lineTable)
    .select('product_id, description, qty, unit_price')
    .eq(parentCol, docId);
  if (error) throw new Error(`lines fetch failed: ${error.message}`);
  return (data ?? []).map((r: Record<string, unknown>) => {
    const row = camelize(r);
    const qty = Number(row.qty ?? 0);
    const unitPrice = Number(row.unitPrice ?? 0);
    return {
      code: String(row.code ?? row.sku ?? ''),
      description: String(row.description ?? ''),
      qty,
      unitPrice,
      total: Number((row.total ?? qty * unitPrice).toFixed(3)),
    };
  });
}

const DOC_TABLEL: Record<DocType, string> = {
  quote: 'quotes',
  invoice: 'customer_invoices',
  delivery: 'delivery_notes',
  purchase_order: 'purchase_orders',
  vendor_bill: 'vendor_bills',
};

const LINE_TABLEL: Record<DocType, string> = {
  quote: 'quote_lines',
  invoice: 'customer_invoice_lines',
  delivery: 'delivery_lines',
  purchase_order: 'purchase_order_lines',
  vendor_bill: 'vendor_bill_lines',
};

const LINE_PARENT_COL: Record<DocType, string> = {
  quote: 'quote_id',
  invoice: 'customer_invoice_id',
  delivery: 'delivery_note_id',
  purchase_order: 'purchase_order_id',
  vendor_bill: 'vendor_bill_id',
};

const PARTY_TABLEL: Record<DocType, 'customers' | 'suppliers'> = {
  quote: 'customers',
  invoice: 'customers',
  delivery: 'customers',
  purchase_order: 'suppliers',
  vendor_bill: 'suppliers',
};

async function fetchDocData(c: SdkClient, docType: DocType, docId: string): Promise<DocData> {
  const docTable = DOC_TABLEL[docType];
  const lineTable = LINE_TABLEL[docType];
  const parentCol = LINE_PARENT_COL[docType];
  const partyTable = PARTY_TABLEL[docType];

  const doc = await fetchOne<Record<string, unknown>>(c, docTable, docId, '*');

  const [party, company, lines] = await Promise.all([
    fetchOne<Record<string, unknown>>(c, partyTable, String(doc.customerId ?? doc.supplierId ?? ''), 'id, name, vat_number'),
    fetchOne<Record<string, unknown>>(c, 'companies', String(doc.companyId ?? ''), 'id, name, vat_number, base_currency'),
    fetchLines(c, lineTable, parentCol, docId),
  ]);

  return {
    number: String(doc.number ?? ''),
    date: String(doc.date ?? ''),
    dueDate: doc.dueDate ? String(doc.dueDate) : undefined,
    validUntil: doc.validUntil ? String(doc.validUntil) : undefined,
    partyType: PARTY_TABLEL[docType],
    partyName: String(party.name ?? ''),
    partyVat: party.vatNumber ? String(party.vatNumber) : undefined,
    companyName: String(company.name ?? ''),
    companyVat: company.vatNumber ? String(company.vatNumber) : undefined,
    currency: String(doc.currency ?? company.baseCurrency ?? 'KWD'),
    lines,
    subtotal: Number(doc.subtotal ?? 0),
    taxTotal: Number(doc.taxTotal ?? 0),
    total: Number(doc.total ?? 0),
    notes: doc.notes ? String(doc.notes) : undefined,
    state: String(doc.state ?? 'draft'),
  };
}

async function fetchFinancialData(
  c: SdkClient,
  type: FinancialType,
  periodId: string,
): Promise<FinancialData> {
  const rpcName =
    type === 'pl' ? 'report_pnl'
    : type === 'balance_sheet' ? 'report_balance_sheet'
    : type === 'cash_flow' ? 'report_cash_flow'
    : 'report_trial_balance';
  const { data, error } = await c.database.rpc(rpcName, { p_period_id: periodId });
  if (error || !data) throw new Error(`${rpcName} failed: ${error?.message ?? 'no data'}`);
  const json = data as { line_items: { label: string; amount: number }[]; totals: Record<string, number> };

  const period = await fetchOne<{ year: number; month: number; companyId: string }>(
    c, 'fiscal_periods', periodId, 'year, month, company_id',
  );
  const company = await fetchOne<{ name: string; baseCurrency: string }>(
    c, 'companies', period.companyId, 'name, base_currency',
  );

  return {
    statementType:
      type === 'pl' ? 'Profit & Loss'
      : type === 'balance_sheet' ? 'Balance Sheet'
      : type === 'cash_flow' ? 'Cash Flow'
      : 'Trial Balance',
    period: `${period.year}-${String(period.month).padStart(2, '00')}`,
    currency: String(company.baseCurrency ?? 'KWD'),
    lineItems: json.line_items ?? [],
    totals: json.totals ?? {},
  };
}

// ─── entry handler (auth, dispatch, preview/save) ───────────────────────────

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

function json(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS, 'Content-Type': 'application/json' },
  });
}

function unauthorized(): Response {
  return json(401, { error: 'Unauthorized' });
}

function badRequest(msg: string): Response {
  return json(400, { error: msg });
}

function isDocInput(body: PdfRequest): body is DocInput {
  return body.docType !== 'financial';
}

function isFinancialInput(body: PdfRequest): body is FinancialInput {
  return body.docType === 'financial';
}

async function handleSave(
  c: SdkClient,
  companyId: string,
  docType: string,
  docId: string,
  locale: PdfLocale,
  state: string,
  bytes: Uint8Array,
): Promise<PdfResponse> {
  const path = `${companyId}/${docType}/${docId}/pdf-${locale}-${state}.pdf`;
  const { data: up, error: upErr } = await c.storage
    .from('documents')
    .upload(path, new Blob([bytes], { type: 'application/pdf' }));
  if (upErr || !up) throw new Error(`storage upload failed: ${upErr?.message ?? 'no data'}`);

  const { data: att, error: attErr } = await c.database
    .from('attachments')
    .insert([{
      company_id: companyId,
      doc_type: docType,
      doc_id: docId,
      bucket: 'documents',
      key: up!.key,
      url: up!.url,
      mime: 'application/pdf',
      size: bytes.length,
      kind: 'generated_pdf',
      template_version: TEMPLATE_VERSION,
    }])
    .select('id')
    .single();
  if (attErr || !att) throw new Error(`attachments insert failed: ${attErr?.message ?? 'no row'}`);

  const { data: signed, error: sErr } = await c.storage
    .from('documents')
    .createSignedUrl(up!.key, 3600);
  if (sErr || !signed) throw new Error(`createSignedUrl failed: ${sErr?.message ?? 'no url'}`);

  return {
    mode: 'save',
    attachmentId: att!.id,
    url: signed!.signedUrl,
    key: up!.key,
  };
}

export default async function (req: Request): Promise<Response> {
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: CORS });
  }
  if (req.method !== 'POST') {
    return json(405, { error: 'Method not allowed' });
  }

  const auth = req.headers.get('Authorization');
  const userToken = auth?.startsWith('Bearer ') ? auth.slice(7) : null;
  if (!userToken) return unauthorized();

  let body: PdfRequest;
  try {
    body = await req.json();
  } catch {
    return badRequest('invalid JSON body');
  }
  if (!body || !body.docType || !body.locale || !body.mode) {
    return badRequest('missing docType, locale, or mode');
  }

  const c = createClient({
    baseUrl: Deno.env.get('INSFORGE_BASE_URL'),
    accessToken: userToken,
    anonKey: Deno.env.get('ANON_KEY'),
  });

  const { data: userData } = await c.auth.getCurrentUser();
  if (!userData?.user?.id) return unauthorized();

  try {
    if (isFinancialInput(body)) {
      if (!body.type || !body.periodId) return badRequest('financial branch requires type and periodId');
      const data = await fetchFinancialData(c, body.type, body.periodId);
      const bytes = await renderFinancial(data, body.locale);
      if (body.mode === 'preview') return new Response(bytes, {
        status: 200,
        headers: { ...CORS, 'Content-Type': 'application/pdf' },
      });
      const saved = await handleSave(c, '', 'financial', body.periodId, body.locale, 'posted', bytes);
      return json(200, saved);
    }

    if (isDocInput(body)) {
      if (!body.docId) return badRequest('doc branch requires docId');
      const data = await fetchDocData(c, body.docType as DocType, body.docId);
      const bytes = await renderDoc(body.docType, data, body.locale);
      if (body.mode === 'preview') return new Response(bytes, {
        status: 200,
        headers: { ...CORS, 'Content-Type': 'application/pdf' },
      });
      const saved = await handleSave(c, data.companyName, body.docType, body.docId, body.locale, data.state, bytes);
      return json(200, saved);
    }

    return badRequest('invalid docType');
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return json(500, { error: `pdf-gen failed: ${msg}` });
  }
}
