// pdf-gen edge function — single-file (InsForge `--file` does not bundle local imports).
// Black/white only (per InvoiceQuickly print best practices + Ahmad).
// Arabic RTL (per Invovate): flip entire page structure, Western numerals stay Latin.
// PDF/A-2b archival (per research). pdfnative block-based API (no JSX, no pdfnative-react).

import {
  buildDocumentPDFBytes,
  registerFonts,
  loadFontData,
  type DocumentBlock,
  type FontEntry,
  type PdfLayoutOptions,
} from 'npm:pdfnative';
import { createClient } from 'npm:@insforge/sdk';

// ─── types ────────────────────────────────────────────────────────────────

type DocType =
  | 'quote'
  | 'invoice'
  | 'delivery'
  | 'purchase_order'
  | 'vendor_bill'
  | 'financial';

type FinancialType = 'pl' | 'balance_sheet' | 'cash_flow' | 'trial_balance' | 'general_ledger';
type PdfLocale = 'en' | 'ar';
type PdfMode = 'preview' | 'save';

type DocInput = {
  docType: DocType;
  docId: string;
  locale: PdfLocale;
  mode: PdfMode;
};

type FinancialInput = {
  docType: 'financial';
  type: FinancialType;
  periodId?: string;
  accountId?: string;
  from?: string;
  to?: string;
  locale: PdfLocale;
  mode: PdfMode;
};

type PdfRequest = DocInput | FinancialInput;

type PdfPreviewResponse = {
  mode: 'preview';
  contentType: 'application/pdf';
  base64: string;
};

type PdfSaveResponse = {
  mode: 'save';
  attachmentId: string;
  url: string;
  key: string;
  cached: boolean;
};

type PdfResponse = PdfPreviewResponse | PdfSaveResponse;

type LineRow = {
  code: string;
  description: string;
  qty: number | string;
  unitPrice: number | string;
  total: number | string;
};

type DocData = {
  companyId: string;
  number: string;
  date: string;
  dueDate?: string;
  validUntil?: string;
  partyType: 'customer' | 'supplier';
  partyName: string;
  partyVat?: string;
  companyName: string;
  companyVat?: string;
  currency: string;
  lines: LineRow[];
  subtotal: number;
  taxTotal: number;
  total: number;
  notes?: string;
  state: string;
};

type FinancialData = {
  companyId: string;
  companyName: string;
  statementType: string;
  period: string;
  currency: string;
  lineItems: { label: string; amount: number }[];
  totals: Record<string, number>;
};

// ─── labels (inline; generated from messages/{en,ar}.json in full build) ──────────

type Labels = {
  docType: string;
  number: string;
  date: string;
  dueDate: string;
  validUntil: string;
  customer: string;
  supplier: string;
  currency: string;
  colCode: string;
  colDescription: string;
  colQty: string;
  colUnitPrice: string;
  colTotal: string;
  subtotal: string;
  tax: string;
  total: string;
  footer: string;
  period: string;
  label: string;
  amount: string;
};

const EN: Labels = {
  docType: 'Quote',
  number: 'Number',
  date: 'Date',
  dueDate: 'Due date',
  validUntil: 'Valid until',
  customer: 'Customer',
  supplier: 'Supplier',
  currency: 'Currency',
  colCode: 'Code',
  colDescription: 'Description',
  colQty: 'Qty',
  colUnitPrice: 'Unit price',
  colTotal: 'Total',
  subtotal: 'Subtotal',
  tax: 'Tax',
  total: 'Total',
  footer: 'Generated by Atmata ERP',
  period: 'Period',
  label: 'Label',
  amount: 'Amount',
};

const AR: Labels = {
  docType: 'عرض سعر',
  number: 'الرقم',
  date: 'التاريخ',
  dueDate: 'تاريخ الاستحقاق',
  validUntil: 'صالح حتى',
  customer: 'العميل',
  supplier: 'المورد',
  currency: 'العملة',
  colCode: 'الرمز',
  colDescription: 'الوصف',
  colQty: 'الكمية',
  colUnitPrice: 'سعر الوحدة',
  colTotal: 'الإجمالي',
  subtotal: 'المجموع الفرعي',
  tax: 'الضريبة',
  total: 'الإجمالي',
  footer: 'تم إنشاؤه بواسطة Atmata ERP',
  period: 'الفترة',
  label: 'البند',
  amount: 'المبلغ',
};

function labelsFor(locale: PdfLocale): Labels {
  return locale === 'ar' ? AR : EN;
}

function docTypeLabel(docType: string, locale: PdfLocale): string {
  const map: Record<string, string> = {
    quote: labelsFor(locale).docType,
    invoice: locale === 'ar' ? 'فاتورة' : 'Invoice',
    delivery: locale === 'ar' ? 'إشعار تسليم' : 'Delivery note',
    purchase_order: locale === 'ar' ? 'أمر شراء' : 'Purchase order',
    vendor_bill: locale === 'ar' ? 'فاتورة المورد' : 'Vendor bill',
    financial: locale === 'ar' ? 'القوائم المالية' : 'Financial statement',
  };
  return map[docType] ?? labelsFor(locale).docType;
}

// ─── fonts (lazy per-locale) ──────────────────────────────────────────────

let fontsRegistered = false;

function ensureFontsRegistered(): void {
  if (fontsRegistered) return;
  registerFonts({
    ar: () => import('npm:pdfnative/fonts/noto-arabic-data.js'),
    latin: () => import('npm:pdfnative/fonts/noto-sans-data.js'),
  });
  fontsRegistered = true;
}

async function loadLocaleFonts(locale: PdfLocale): Promise<FontEntry[]> {
  ensureFontsRegistered();
  const latin = await loadFontData('latin');
  if (!latin) throw new Error('latin font failed to load');
  // /F1 and /F2 are reserved by pdfnative (base-14 fonts). Custom CIDFont
  // entries must use /F3+ with a leading slash, otherwise the resource name
  // is malformed and the content-stream Tf operator resolves to the reserved
  // base Helvetica (WinAnsi) — the 2-byte Identity-H GIDs are then read as
  // single-byte WinAnsi chars, shifting every ASCII glyph by −29.
  if (locale === 'en') return [{ fontData: latin, fontRef: '/F3', lang: 'latin' }];
  const ar = await loadFontData('ar');
  if (!ar) throw new Error('arabic font failed to load');
  return [
    { fontData: ar, fontRef: '/F4', lang: 'ar' },
    { fontData: latin, fontRef: '/F3', lang: 'latin' },
  ];
}

// ─── templates (block-based, black/white only) ───────────────────────────

const BW = {
  black: '#000000' as const,
  gray: '#666666' as const,
  lightBorder: '#CCCCCC' as const,
  altRow: '#F5F5F5' as const,
  white: '#FFFFFF' as const,
};

function lineItemsTable(lines: LineRow[], L: Labels, isAr: boolean): DocumentBlock {
  const headers = isAr
    ? [L.colCode, L.colDescription, L.colQty, L.colUnitPrice, L.colTotal]
    : ['Code', 'Description', 'Qty', 'Unit price', 'Total'];
  return {
    type: 'table',
    headers,
    rows: lines.map((l) => ({
      cells: [l.code, l.description, String(l.qty), String(l.unitPrice), String(l.total)],
    })),
    columns: [
      { f: 0.12, a: 'l' },
      { f: 0.40, a: 'l' },
      { f: 0.12, a: isAr ? 'r' : 'c' },
      { f: 0.18, a: 'r' },
      { f: 0.18, a: 'r' },
    ],
  };
}

function partyBlock(data: DocData, L: Labels, isAr: boolean): DocumentBlock {
  const partyLabel = data.partyType === 'supplier' ? L.supplier : L.customer;
  const dateLabel = data.dueDate ? L.dueDate : L.validUntil;
  const dateValue = data.dueDate ?? data.validUntil ?? data.date;
  const lines = [
    `${partyLabel}: ${data.partyName}`,
    data.partyVat ? `${L.currency}: ${data.currency}` : '',
    `${L.number}: ${data.number}`,
    `${L.date}: ${data.date}`,
    dateValue ? `${dateLabel}: ${dateValue}` : '',
  ].filter(Boolean);
  return {
    type: 'paragraph',
    text: lines.join('  ·  '),
    align: isAr ? 'right' : 'left',
    color: BW.gray,
  };
}

function totalsBlock(data: DocData, L: Labels, isAr: boolean): DocumentBlock {
  return {
    type: 'paragraph',
    text: [
      `${L.subtotal}: ${data.currency} ${data.subtotal}`,
      `${L.tax}: ${data.currency} ${data.taxTotal}`,
      `${L.total}: ${data.currency} ${data.total}`,
    ].join('  ·  '),
    align: isAr ? 'right' : 'left',
    color: BW.black,
  };
}

function buildDocBlocks(
  docType: string,
  data: DocData,
  L: Labels,
  locale: PdfLocale,
): DocumentBlock[] {
  const isAr = locale === 'ar';
  const title = `${docTypeLabel(docType, locale)} ${data.number}`;
  const blocks: DocumentBlock[] = [
    { type: 'heading', text: title, level: 1, color: BW.black },
    partyBlock(data, L, isAr),
    { type: 'spacer', height: 12 },
    lineItemsTable(data.lines, L, isAr),
    { type: 'spacer', height: 12 },
    totalsBlock(data, L, isAr),
  ];
  if (data.notes) blocks.push({ type: 'paragraph', text: data.notes, color: BW.gray });
  blocks.push({ type: 'paragraph', text: L.footer, color: BW.gray });
  return blocks;
}

function buildFinancialBlocks(
  data: FinancialData,
  L: Labels,
  locale: PdfLocale,
): DocumentBlock[] {
  const isAr = locale === 'ar';
  const blocks: DocumentBlock[] = [
    { type: 'heading', text: `${data.statementType} — ${data.period}`, level: 1, color: BW.black },
    {
      type: 'paragraph',
      text: `${L.currency}: ${data.currency}`,
      align: isAr ? 'right' : 'left',
      color: BW.gray,
    },
    { type: 'spacer', height: 12 },
    {
      type: 'table',
      headers: isAr ? [L.label, L.amount] : ['Label', 'Amount'],
      rows: data.lineItems.map((li) => ({ cells: [li.label, String(li.amount)] })),
      columns: [
        { f: 0.6, a: 'l' },
        { f: 0.4, a: 'r' },
      ],
    },
    { type: 'spacer', height: 12 },
    {
      type: 'paragraph',
      text: Object.entries(data.totals)
        .map(([k, v]) => `${k}: ${data.currency} ${v}`)
        .join('  ·  '),
      align: isAr ? 'right' : 'left',
      color: BW.black,
    },
    { type: 'paragraph', text: L.footer, color: BW.gray },
  ];
  return blocks;
}

// ─── render (B/W colors, PDF/A-2b, RTL for ar) ────────────────────────────

const TEMPLATE_VERSION = 'sha256:9fa58346c397f250'; // generated by scripts/pdf-template-version.mjs

const BW_COLORS = {
  title: BW.black,
  credit: BW.black,
  debit: BW.black,
  text: BW.black,
  thBg: BW.white,
  thBrd: BW.black,
  rowBrd: BW.lightBorder,
  ptdBg: BW.white,
  balBg: BW.altRow,
  balBrd: BW.black,
  label: BW.gray,
  footer: BW.gray,
};

function pageHeader(title: string, companyName: string, isAr: boolean) {
  return {
    left: isAr ? '' : companyName,
    center: '',
    right: isAr ? companyName : title,
  };
}

function pageFooter(footerText: string) {
  return { left: footerText, right: 'Page {page} of {pages}' };
}

async function renderDoc(docType: string, data: DocData, locale: PdfLocale): Promise<Uint8Array> {
  const L = labelsFor(locale);
  const isAr = locale === 'ar';
  const title = `${docTypeLabel(docType, locale)} ${data.number}`;
  const blocks = buildDocBlocks(docType, data, L, locale);
  const fontEntries = await loadLocaleFonts(locale);
  const layout: Partial<PdfLayoutOptions> = {
    direction: isAr ? 'r2l' : 'l2r',
    tagged: 'pdfa2b',
    colors: BW_COLORS,
    headerTemplate: pageHeader(title, data.companyName, isAr),
    footerTemplate: pageFooter(L.footer),
  };
  return buildDocumentPDFBytes(
    { docTitle: title, title, blocks, footerText: L.footer, fontEntries },
    layout,
  );
}

async function renderFinancial(data: FinancialData, locale: PdfLocale): Promise<Uint8Array> {
  const L = labelsFor(locale);
  const isAr = locale === 'ar';
  const title = `${data.statementType} — ${data.period}`;
  const blocks = buildFinancialBlocks(data, L, locale);
  const fontEntries = await loadLocaleFonts(locale);
  const layout: Partial<PdfLayoutOptions> = {
    direction: isAr ? 'r2l' : 'l2r',
    tagged: 'pdfa2b',
    colors: BW_COLORS,
    headerTemplate: pageHeader(title, data.companyName, isAr),
    footerTemplate: pageFooter(L.footer),
  };
  return buildDocumentPDFBytes(
    { docTitle: title, title, blocks, footerText: L.footer, fontEntries },
    layout,
  );
}

// ─── data fetch (RLS-scoped via user token) ───────────────────────────────

type SdkClient = ReturnType<typeof createClient>;

class FunctionFailure extends Error {
  constructor(
    readonly code: 'NOT_FOUND' | 'CONFLICT' | 'STORAGE_FAILED' | 'UNAVAILABLE' | 'INTERNAL',
    readonly status: number,
    readonly retryable = false,
  ) {
    super(code);
  }
}

function camelize<T = Record<string, unknown>>(row: T): T {
  const out: Record<string, unknown> = {};
  for (const k of Object.keys(row)) {
    const camel = k.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
    out[camel] = row[k];
  }
  return out as T;
}

async function fetchOne<T = Record<string, unknown>>(
  c: SdkClient,
  table: string,
  id: string,
  select: string,
): Promise<T> {
  const { data, error } = await c.database
    .from(table)
    .select(select)
    .eq('id', id)
    .single();
  if (error || !data) throw new FunctionFailure('NOT_FOUND', 404);
  return camelize(data as T);
}

async function fetchLines(
  c: SdkClient,
  lineTable: string,
  parentCol: string,
  docId: string,
): Promise<LineRow[]> {
  const { data, error } = await c.database
    .from(lineTable)
    .select('product_id, description, qty, qty_delivered, unit_price')
    .eq(parentCol, docId);
  if (error) throw new FunctionFailure('UNAVAILABLE', 503, true);
  const rows = data ?? [];
  const productIds = [...new Set(rows.map((row: Record<string, unknown>) => String(row.product_id ?? '')).filter(Boolean))];
  const productMap = new Map<string, { sku?: string; name?: string }>();
  if (productIds.length > 0) {
    const { data: products, error: productError } = await c.database
      .from('products')
      .select('id, sku, name')
      .in('id', productIds);
    if (productError) throw new FunctionFailure('UNAVAILABLE', 503, true);
    for (const product of products ?? []) {
      productMap.set(String(product.id), product as { sku?: string; name?: string });
    }
  }
  return rows.map((r: Record<string, unknown>) => {
    const row = camelize(r);
    const product = productMap.get(String(row.productId ?? ''));
    const qty = Number(row.qtyDelivered ?? row.qty ?? 0);
    const unitPrice = Number(row.unitPrice ?? 0);
    return {
      code: String(product?.sku ?? ''),
      description: String(row.description ?? product?.name ?? ''),
      qty,
      unitPrice,
      total: Number((row.total ?? qty * unitPrice).toFixed(3)),
    };
  });
}

const DOC_TABLEL: Record<Exclude<DocType, 'financial'>, string> = {
  quote: 'quotes',
  invoice: 'customer_invoices',
  delivery: 'delivery_notes',
  purchase_order: 'purchase_orders',
  vendor_bill: 'vendor_bills',
};

const LINE_TABLEL: Record<Exclude<DocType, 'financial'>, string> = {
  quote: 'quote_lines',
  invoice: 'customer_invoice_lines',
  delivery: 'delivery_note_lines',
  purchase_order: 'purchase_order_lines',
  vendor_bill: 'vendor_bill_lines',
};

const LINE_PARENT_COL: Record<Exclude<DocType, 'financial'>, string> = {
  quote: 'quote_id',
  invoice: 'customer_invoice_id',
  delivery: 'delivery_note_id',
  purchase_order: 'purchase_order_id',
  vendor_bill: 'vendor_bill_id',
};

const PARTY_TABLEL: Record<Exclude<DocType, 'financial'>, 'customers' | 'suppliers'> = {
  quote: 'customers',
  invoice: 'customers',
  delivery: 'customers',
  purchase_order: 'suppliers',
  vendor_bill: 'suppliers',
};

async function fetchDocData(c: SdkClient, docType: Exclude<DocType, 'financial'>, docId: string): Promise<DocData> {
  const docTable = DOC_TABLEL[docType];
  const lineTable = LINE_TABLEL[docType];
  const parentCol = LINE_PARENT_COL[docType];
  const partyTable = PARTY_TABLEL[docType];

  const doc = await fetchOne<Record<string, unknown>>(c, docTable, docId, '*');

  const [party, company, lines] = await Promise.all([
    fetchOne<Record<string, unknown>>(c, partyTable, String(doc.customerId ?? doc.supplierId ?? ''), 'id, name, vat_number'),
    fetchOne<Record<string, unknown>>(c, 'companies', String(doc.companyId ?? ''), 'id, name, vat_number, base_currency'),
    fetchLines(c, lineTable, parentCol, docId),
  ]);

  return {
    companyId: String(company.id ?? ''),
    number: String(doc.number ?? ''),
    date: String(doc.date ?? ''),
    dueDate: doc.dueDate ? String(doc.dueDate) : undefined,
    validUntil: doc.validUntil ? String(doc.validUntil) : undefined,
    partyType: PARTY_TABLEL[docType] === 'suppliers' ? 'supplier' : 'customer',
    partyName: String(party.name ?? ''),
    partyVat: party.vatNumber ? String(party.vatNumber) : undefined,
    companyName: String(company.name ?? ''),
    companyVat: company.vatNumber ? String(company.vatNumber) : undefined,
    currency: String(doc.currency ?? company.baseCurrency ?? 'KWD'),
    lines,
    subtotal: Number(doc.subtotal ?? 0),
    taxTotal: Number(doc.taxTotal ?? 0),
    total: Number(doc.total ?? 0),
    notes: doc.notes ? String(doc.notes) : undefined,
    state: String(doc.state ?? 'draft'),
  };
}

async function fetchFinancialData(
  c: SdkClient,
  type: FinancialType,
  opts: {
    periodId?: string;
    accountId?: string;
    from?: string;
    to?: string;
  },
): Promise<FinancialData> {
  const periodId = opts.periodId;
  const rpcArgs: Record<string, unknown> = {};
  if (periodId) rpcArgs.p_period_id = periodId;
  if (opts.accountId) rpcArgs.p_account_id = opts.accountId;
  if (opts.from) rpcArgs.p_from = opts.from;
  if (opts.to) rpcArgs.p_to = opts.to;

  const rpcName =
    type === 'pl' ? 'report_pnl'
    : type === 'balance_sheet' ? 'report_balance_sheet'
    : type === 'cash_flow' ? 'report_cash_flow'
    : type === 'general_ledger' ? 'report_general_ledger'
    : 'report_trial_balance';

  const { data, error } = await c.database.rpc(
    rpcName,
    type === 'trial_balance' || type === 'general_ledger'
      ? rpcArgs
      : { p_period_id: periodId },
  );
  if (error || !data) throw new FunctionFailure('UNAVAILABLE', 503, true);

  let lineItems: { label: string; amount: number }[] = [];
  let totals: Record<string, number> = {};

  if (type === 'general_ledger') {
    const rows = data as Array<Record<string, unknown>>;
    lineItems = rows.map((row) => {
      const entryDate = String(row.entry_date ?? row.entryDate ?? '');
      const journalNumber = String(row.journal_number ?? row.journalNumber ?? '');
      const code = String(row.account_code ?? row.accountCode ?? '');
      const name = String(row.account_name ?? row.accountName ?? '');
      const debit = Number(row.debit ?? 0);
      const credit = Number(row.credit ?? 0);
      const side =
        debit > 0 && credit > 0
          ? `Dr ${debit} / Cr ${credit}`
          : debit > 0
            ? `Dr ${debit}`
            : `Cr ${credit}`;
      return {
        label: `${entryDate} | ${journalNumber} | ${`${code} ${name}`.trim()} | ${side}`,
        amount: Number(row.running_balance ?? row.runningBalance ?? 0),
      };
    });
    totals = {
      debit: rows.reduce((sum, row) => sum + Number(row.debit ?? 0), 0),
      credit: rows.reduce((sum, row) => sum + Number(row.credit ?? 0), 0),
    };
  } else if (type === 'trial_balance') {
    const rows = data as Array<Record<string, unknown>>;
    lineItems = rows.map((row) => ({
      label: `${row.account_code ?? row.accountCode ?? ''} ${row.account_name ?? row.accountName ?? ''}`.trim(),
      amount: Number(row.balance ?? 0),
    }));
    totals = {
      debit: rows.reduce((sum, row) => sum + Number(row.debit ?? 0), 0),
      credit: rows.reduce((sum, row) => sum + Number(row.credit ?? 0), 0),
    };
  } else {
    const json = data as { line_items: { label: string; amount: number }[]; totals: Record<string, number> };
    lineItems = json.line_items ?? [];
    totals = json.totals ?? {};
  }

  let companyId: string;
  let periodLabel: string;
  if (periodId) {
    const period = await fetchOne<{ year: number; month: number; companyId: string }>(
      c, 'fiscal_periods', periodId, 'year, month, company_id',
    );
    companyId = String(period.companyId);
    periodLabel = `${period.year}-${String(period.month).padStart(2, '0')}`;
  } else {
    const { data: memberData, error: memberError } = await c.database
      .from('company_members')
      .select('company_id')
      .eq('active', true)
      .limit(1)
      .maybeSingle();
    if (memberError || !memberData) throw new FunctionFailure('UNAVAILABLE', 503, true);
    companyId = String((memberData as { company_id?: string; companyId?: string }).company_id
      ?? (memberData as { companyId?: string }).companyId);
    const parts = [opts.from, opts.to].filter(Boolean);
    periodLabel = parts.length > 0 ? parts.join(' – ') : 'All periods';
  }

  const company = await fetchOne<{ id: string; name: string; baseCurrency: string }>(
    c, 'companies', companyId, 'id, name, base_currency',
  );

  return {
    companyId: String(company.id),
    companyName: String(company.name),
    statementType:
      type === 'pl' ? 'Profit & Loss'
      : type === 'balance_sheet' ? 'Balance Sheet'
      : type === 'cash_flow' ? 'Cash Flow'
      : type === 'general_ledger' ? 'General Ledger'
      : 'Trial Balance',
    period: periodLabel,
    currency: String(company.baseCurrency ?? 'KWD'),
    lineItems,
    totals,
  };
}

// ─── entry handler (auth, dispatch, preview/save) ───────────────────────────

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

function json(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS, 'Content-Type': 'application/json' },
  });
}

function failure(
  status: number,
  code: string,
  requestId: string,
  retryable = false,
): Response {
  const messageKey: Record<string, string> = {
    UNAUTHENTICATED: 'errors.unauthenticated',
    VALIDATION: 'errors.validation',
    NOT_FOUND: 'errors.notFound',
    CONFLICT: 'errors.conflict',
    STORAGE_FAILED: 'errors.storageFailed',
    UNAVAILABLE: 'errors.unavailable',
    INTERNAL: 'errors.internal',
  };
  return json(status, {
    error: {
      code,
      messageKey: messageKey[code] ?? 'errors.internal',
      requestId,
      retryable,
    },
  });
}

function unauthorized(requestId: string): Response {
  return failure(401, 'UNAUTHENTICATED', requestId);
}

const DOC_TYPES = new Set(['quote', 'invoice', 'delivery', 'purchase_order', 'vendor_bill']);
const FINANCIAL_TYPES = new Set(['pl', 'balance_sheet', 'cash_flow', 'trial_balance', 'general_ledger']);

function parseRequest(value: unknown): PdfRequest | null {
  if (!value || typeof value !== 'object') return null;
  const body = value as Record<string, unknown>;
  if ((body.locale !== 'en' && body.locale !== 'ar') || (body.mode !== 'preview' && body.mode !== 'save')) {
    return null;
  }
  if (body.docType === 'financial') {
    if (typeof body.type !== 'string' || !FINANCIAL_TYPES.has(body.type)) return null;
    const periodId = body.periodId;
    const accountId = body.accountId;
    const from = body.from;
    const to = body.to;
    const hasPeriod =
      typeof periodId === 'string' && periodId.length >= 1 && periodId.length <= 160;
    const hasAccount =
      typeof accountId === 'string' && accountId.length >= 1 && accountId.length <= 160;
    const hasFrom = typeof from === 'string' && from.length >= 1 && from.length <= 32;
    const hasTo = typeof to === 'string' && to.length >= 1 && to.length <= 32;
    const hasFilters = hasAccount || hasFrom || hasTo;
    if (body.type === 'trial_balance') {
      if (!hasPeriod && !hasFilters) return null;
    } else if (!hasPeriod) {
      return null;
    }
    if (periodId !== undefined && !hasPeriod) return null;
    if (accountId !== undefined && !hasAccount) return null;
    if (from !== undefined && !hasFrom) return null;
    if (to !== undefined && !hasTo) return null;
    return {
      docType: 'financial',
      type: body.type as FinancialType,
      periodId: hasPeriod ? (periodId as string) : undefined,
      accountId: hasAccount ? (accountId as string) : undefined,
      from: hasFrom ? (from as string) : undefined,
      to: hasTo ? (to as string) : undefined,
      locale: body.locale as PdfLocale,
      mode: body.mode as PdfMode,
    };
  }
  if (
    typeof body.docType !== 'string' ||
    !DOC_TYPES.has(body.docType) ||
    typeof body.docId !== 'string' ||
    body.docId.length < 1 ||
    body.docId.length > 160
  ) return null;
  return body as DocInput;
}

function isFinancialInput(body: PdfRequest): body is FinancialInput {
  return body.docType === 'financial';
}

function stableStringify(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`;
  if (value && typeof value === 'object') {
    return `{${Object.entries(value as Record<string, unknown>)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, item]) => `${JSON.stringify(key)}:${stableStringify(item)}`)
      .join(',')}}`;
  }
  return JSON.stringify(value);
}

async function hashData(value: unknown): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(stableStringify(value)));
  return [...new Uint8Array(digest)]
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('')
    .slice(0, 24);
}

function bytesToBase64(bytes: Uint8Array): string {
  let binary = '';
  const size = 0x8000;
  for (let i = 0; i < bytes.length; i += size) {
    binary += String.fromCharCode(...bytes.subarray(i, i + size));
  }
  return btoa(binary);
}

async function handleSave(
  c: SdkClient,
  companyId: string,
  docType: string,
  docId: string,
  locale: PdfLocale,
  state: string,
  dataHash: string,
  bytes: Uint8Array,
): Promise<PdfResponse> {
  const path = `${companyId}/${docType}/${docId}/pdf-${locale}-${state}-${TEMPLATE_VERSION.replace(':', '-')}-${dataHash}.pdf`;

  const findCached = async () => {
    const { data, error } = await c.database
      .from('attachments')
      .select('id, key')
      .eq('company_id', companyId)
      .eq('doc_type', docType)
      .eq('doc_id', docId)
      .eq('kind', 'generated_pdf')
      .eq('template_version', TEMPLATE_VERSION)
      .eq('key', path)
      .maybeSingle();
    if (error) throw new FunctionFailure('UNAVAILABLE', 503, true);
    return data as { id: string; key: string } | null;
  };
  const signedResult = async (attachment: { id: string; key: string }, cached: boolean): Promise<PdfSaveResponse> => {
    const { data: signed, error: signedError } = await c.storage
      .from('documents')
      .createSignedUrl(attachment.key, 3600);
    if (signedError || !signed) throw new FunctionFailure('STORAGE_FAILED', 502, true);
    return {
      mode: 'save',
      attachmentId: attachment.id,
      url: signed.signedUrl,
      key: attachment.key,
      cached,
    };
  };

  const existing = await findCached();
  if (existing) return signedResult(existing, true);

  const { data: up, error: upErr } = await c.storage
    .from('documents')
    .upload(path, new Blob([bytes], { type: 'application/pdf' }));
  if (upErr || !up) throw new FunctionFailure('STORAGE_FAILED', 502, true);

  if (up.key !== path) {
    for (let attempt = 0; attempt < 4; attempt += 1) {
      await new Promise((resolve) => setTimeout(resolve, 75 * (attempt + 1)));
      const winner = await findCached();
      if (winner) {
        await c.storage.from('documents').remove(up.key);
        return signedResult(winner, true);
      }
    }
    await c.storage.from('documents').remove(up.key);
    throw new FunctionFailure('CONFLICT', 409, true);
  }

  const { data: att, error: attErr } = await c.database
    .from('attachments')
    .insert([{
      company_id: companyId,
      doc_type: docType,
      doc_id: docId,
      bucket: 'documents',
      key: path,
      url: up.url,
      mime: 'application/pdf',
      size: bytes.length,
      kind: 'generated_pdf',
      template_version: TEMPLATE_VERSION,
    }])
    .select('id')
    .single();
  if (attErr || !att) {
    const winner = await findCached();
    if (winner) return signedResult(winner, true);
    throw new FunctionFailure('CONFLICT', 409, true);
  }
  return signedResult({ id: att.id, key: path }, false);
}

export default async function (req: Request): Promise<Response> {
  const requestId = crypto.randomUUID();
  const startedAt = Date.now();
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: CORS });
  }
  if (req.method !== 'POST') {
    return failure(405, 'VALIDATION', requestId);
  }

  const auth = req.headers.get('Authorization');
  const userToken = auth?.startsWith('Bearer ') ? auth.slice(7) : null;
  if (!userToken) return unauthorized(requestId);

  let rawBody: unknown;
  try {
    rawBody = await req.json();
  } catch {
    return failure(400, 'VALIDATION', requestId);
  }
  const body = parseRequest(rawBody);
  if (!body) return failure(400, 'VALIDATION', requestId);

  const c = createClient({
    baseUrl: Deno.env.get('INSFORGE_BASE_URL'),
    accessToken: userToken,
    anonKey: Deno.env.get('ANON_KEY'),
  });

  const { data: userData } = await c.auth.getCurrentUser();
  if (!userData?.user?.id) return unauthorized(requestId);

  try {
    if (isFinancialInput(body)) {
      const data = await fetchFinancialData(c, body.type, {
        periodId: body.periodId,
        accountId: body.accountId,
        from: body.from,
        to: body.to,
      });
      const bytes = await renderFinancial(data, body.locale);
      const saveDocId =
        body.periodId ??
        `tb-${body.accountId ?? 'all'}-${body.from ?? ''}-${body.to ?? ''}`;
      if (body.mode === 'preview') {
        console.info(JSON.stringify({ requestId, function: 'pdf-gen', operation: 'preview', companyId: data.companyId, userId: userData.user.id, documentId: saveDocId, durationMs: Date.now() - startedAt, resultCode: 'OK' }));
        return json(200, { mode: 'preview', contentType: 'application/pdf', base64: bytesToBase64(bytes) });
      }
      const saved = await handleSave(c, data.companyId, 'financial', saveDocId, body.locale, 'posted', await hashData(data), bytes);
      return json(200, saved);
    }

    {
      const data = await fetchDocData(c, body.docType, body.docId);
      const bytes = await renderDoc(body.docType, data, body.locale);
      if (body.mode === 'preview') {
        console.info(JSON.stringify({ requestId, function: 'pdf-gen', operation: 'preview', companyId: data.companyId, userId: userData.user.id, documentId: body.docId, durationMs: Date.now() - startedAt, resultCode: 'OK' }));
        return json(200, { mode: 'preview', contentType: 'application/pdf', base64: bytesToBase64(bytes) });
      }
      const saved = await handleSave(c, data.companyId, body.docType, body.docId, body.locale, data.state, await hashData(data), bytes);
      console.info(JSON.stringify({ requestId, function: 'pdf-gen', operation: 'save', companyId: data.companyId, userId: userData.user.id, documentId: body.docId, durationMs: Date.now() - startedAt, cacheHit: saved.mode === 'save' ? saved.cached : false, resultCode: 'OK' }));
      return json(200, saved);
    }
  } catch (e) {
    const known = e instanceof FunctionFailure ? e : new FunctionFailure('INTERNAL', 500);
    console.error(JSON.stringify({ requestId, function: 'pdf-gen', durationMs: Date.now() - startedAt, resultCode: known.code }));
    return failure(known.status, known.code, requestId, known.retryable);
  }
}
