#!/usr/bin/env python3
# Build a normal-looking quote PDF (en + ar) using reportlab.
# Arabic: arabic_reshaper + python-bidi + Noto Sans Arabic (Google OFL).
# Latin numerals stay Latin per kuwaiti-english-mixing.
# Run: python3 scripts/build-quote-pdf.py

import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_RIGHT, TA_CENTER
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Frame, PageTemplate,
)

import arabic_reshaper
from bidi.algorithm import get_display

FONT_DIR = os.path.join(os.path.dirname(__file__), "..", "assets", "fonts")
FONT_DIR = os.path.abspath(FONT_DIR)

pdfmetrics.registerFont(TTFont("NotoSans", os.path.join(FONT_DIR, "NotoSans-Regular.ttf")))
pdfmetrics.registerFont(TTFont("NotoSansArabic", os.path.join(FONT_DIR, "NotoSansArabic-Regular.ttf")))

# ─── seed data (qt_1) ──────────────────────────────────────────────────────
QT = {
    "number": "QT-2026-00001",
    "customer_en": "Areej Bookstore",
    "customer_ar": "متجر أريج للكتب",
    "date": "2026-04-05",
    "valid_until": "2026-05-05",
    "currency": "KWD",
    "lines": [
        {"code": "DC-2D", "description": "Display cooler — 2 door", "qty": 2, "unit_price": 890, "total": 1780},
    ],
    "subtotal": 1780,
    "tax": 89,
    "total": 1869,
}

# ─── labels ─────────────────────────────────────────────────────────────────
EN = {
    "title": "QUOTE",
    "number": "Number",
    "customer": "Customer",
    "date": "Date",
    "valid_until": "Valid until",
    "currency": "Currency",
    "headers": ["Code", "Description", "Qty", "Unit price", "Total"],
    "subtotal": "Subtotal",
    "tax": "Tax",
    "total": "Total",
    "footer": "Generated by Atmata ERP — Quote valid until the date shown",
}

AR = {
    "title": "عرض سعر",
    "number": "الرقم",
    "customer": "العميل",
    "date": "التاريخ",
    "valid_until": "صالح حتى",
    "currency": "العملة",
    "headers": ["الرمز", "الوصف", "الكمية", "سعر الوحدة", "الإجمالي"],
    "subtotal": "المجموع الفرعي",
    "tax": "الضريبة",
    "total": "الإجمالي",
    "footer": "تم إنشاؤه بواسطة Atmata ERP — عرض سعر صالح حتى تاريخه",
}


def shape_ar(text: str) -> str:
    """Reshape Arabic + apply BiDi so reportlab renders joined glyphs RTL."""
    reshaped = arabic_reshaper.reshape(text)
    return get_display(reshaped)


def build_quote_pdf(locale: str, out_path: str) -> None:
    is_ar = locale == "ar"
    L = AR if is_ar else EN
    font_name = "NotoSansArabic" if is_ar else "NotoSans"
    align = TA_RIGHT if is_ar else TA_LEFT
    page_w, page_h = A4
    margin = 18 * mm

    doc = SimpleDocTemplate(
        out_path,
        pagesize=A4,
        leftMargin=margin,
        rightMargin=margin,
        topMargin=margin,
        bottomMargin=margin,
        title=f"{L['title']} {QT['number']}",
        author="Atmata ERP",
    )

    title_style = ParagraphStyle(
        "title", fontName=font_name, fontSize=22, leading=28,
        alignment=align, textColor=colors.HexColor("#1A1423"),
    )
    label_style = ParagraphStyle(
        "label", fontName=font_name, fontSize=10, leading=14,
        alignment=align, textColor=colors.HexColor("#666666"),
    )
    value_style = ParagraphStyle(
        "value", fontName=font_name, fontSize=11, leading=15,
        alignment=align, textColor=colors.HexColor("#1A1423"),
    )
    footer_style = ParagraphStyle(
        "footer", fontName=font_name, fontSize=9, leading=12,
        alignment=align, textColor=colors.HexColor("#999999"),
    )

    def t(s: str) -> str:
        return shape_ar(s) if is_ar else s

    story = []

    # Title
    story.append(Paragraph(t(L["title"]), title_style))
    story.append(Spacer(1, 4 * mm))

    # Party + meta info as a 2-column table
    customer = QT["customer_ar"] if is_ar else QT["customer_en"]
    meta_rows = [
        [t(L["number"]), QT["number"]],
        [t(L["customer"]), t(customer)],
        [t(L["date"]), QT["date"]],
        [t(L["valid_until"]), QT["valid_until"]],
        [t(L["currency"]), QT["currency"]],
    ]
    # For Arabic, flip column order so labels sit on the right
    if is_ar:
        meta_rows = [[v, k] for k, v in meta_rows]

    meta_tbl = Table(meta_rows, colWidths=[40 * mm, 60 * mm])
    meta_tbl.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), font_name),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#666666")),
        ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#1A1423")),
        ("ALIGN", (0, 0), (-1, -1), "RIGHT" if is_ar else "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(meta_tbl)
    story.append(Spacer(1, 8 * mm))

    # Line items table — for Arabic, reverse EVERY row (headers + data) so the
    # table reads right-to-left visually: Code on the right, Total on the left.
    headers = [t(h) for h in L["headers"]]
    if is_ar:
        headers = list(reversed(headers))
    rows = [headers]
    for line in QT["lines"]:
        cells = [
            line["code"],
            t(line["description"]) if is_ar else line["description"],
            str(line["qty"]),
            f"{line['unit_price']:,}",
            f"{line['total']:,}",
        ]
        if is_ar:
            cells = list(reversed(cells))
        rows.append(cells)

    col_widths = [25 * mm, 70 * mm, 20 * mm, 25 * mm, 25 * mm]
    if is_ar:
        col_widths = list(reversed(col_widths))

    line_tbl = Table(rows, colWidths=col_widths, repeatRows=1)
    line_style = TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), font_name),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1A1423")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        # In RTL table, col 0 is now Total (rightmost visually? No — col 0 is leftmost
        # physically, but we reversed so col 0 = Total). Right-align numeric cols,
        # left-align text cols — but since reversed, text cols are now on the right.
        ("ALIGN", (0, 1), (1, -1), "RIGHT" if is_ar else "LEFT"),  # code+desc
        ("ALIGN", (2, 1), (2, -1), "CENTER"),  # qty
        ("ALIGN", (3, 1), (-1, -1), "LEFT" if is_ar else "RIGHT"),  # prices
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F0E8")]),
        ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#1A1423")),
        ("LINEBELOW", (0, 1), (-1, -1), 0.25, colors.HexColor("#CCCCCC")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ])
    line_tbl.setStyle(line_style)
    story.append(line_tbl)
    story.append(Spacer(1, 6 * mm))

    # Totals
    total_rows = [
        [t(L["subtotal"]), f"{QT['subtotal']:,}"],
        [t(L["tax"]), f"{QT['tax']:,}"],
        [t(L["total"]), f"{QT['total']:,}"],
    ]
    if is_ar:
        total_rows = [[v, k] for k, v in total_rows]

    total_tbl = Table(total_rows, colWidths=[40 * mm, 40 * mm])
    total_tbl.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), font_name),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (0, 0), (-1, -1), "RIGHT" if is_ar else "RIGHT"),
        ("ALIGN", (0, 0), (0, -1), "RIGHT" if is_ar else "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#666666")),
        ("LINEABOVE", (0, -1), (-1, -1), 0.5, colors.HexColor("#1A1423")),
        ("FONTNAME", (0, -1), (-1, -1), font_name),
        ("FONTSIZE", (0, -1), (-1, -1), 12),
        ("TEXTCOLOR", (0, -1), (-1, -1), colors.HexColor("#1A1423")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    # Right-align the totals block on the page
    totals_wrap = Table([[total_tbl]], colWidths=[doc.width])
    totals_wrap.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "RIGHT" if not is_ar else "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(totals_wrap)
    story.append(Spacer(1, 10 * mm))

    # Footer
    story.append(Paragraph(t(L["footer"]), footer_style))

    doc.build(story)


if __name__ == "__main__":
    out_dir = "/tmp"
    for locale in ("en", "ar"):
        out = os.path.join(out_dir, f"atmata-quote-{locale}.pdf")
        build_quote_pdf(locale, out)
        size = os.path.getsize(out)
        print(f"{locale.upper()}: {size} bytes -> {out}")
    print("Open both PDFs and verify: Arabic letters joined, RTL layout, Latin numbers, normal invoice look.")
