/**
 * Generates migrations/20260809080000_seed-demo-co1.sql from src/mocks/seed/*.
 * Only co_1 (Atmata Trading Co., KW). Re-run: npx tsx scripts/generate-demo-seed.ts
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { APPROVAL_RULES } from "../src/mocks/seed/approvals";
import { AUDIT_EVENTS } from "../src/mocks/seed/audit";
import { FX_RATES } from "../src/mocks/seed/fx";
import { ACCOUNTS, JOURNAL_ENTRIES } from "../src/mocks/seed/gl";
import {
  INTERNAL_TRANSFERS,
  STOCK_ADJUSTMENTS,
  STOCK_MOVES,
} from "../src/mocks/seed/inv";
import {
  BANK_ACCOUNTS,
  BRANCHES,
  COMPANIES,
  CUSTOMERS,
  FISCAL_PERIODS,
  LOCATIONS,
  PAYMENT_TERMS,
  PRODUCTS,
  SUPPLIERS,
  TAX_CODES,
  WAREHOUSES,
} from "../src/mocks/seed/master";
import {
  GOODS_RECEIPTS,
  PURCHASE_ORDERS,
  PURCHASE_REQUISITIONS,
  VENDOR_BILLS,
  VENDOR_PAYMENTS,
} from "../src/mocks/seed/p2p";
import {
  CUSTOMER_INVOICES,
  CUSTOMER_RECEIPTS,
  DELIVERY_NOTES,
  OPPORTUNITIES,
  QUOTES,
  SALES_ORDERS,
} from "../src/mocks/seed/q2c";
import {
  CREDIT_NOTES,
  CUSTOMER_RETURNS,
  DEBIT_NOTES,
  VENDOR_RETURNS,
} from "../src/mocks/seed/returns";
import { RFQS } from "../src/mocks/seed/rfq";

const CO = "co_1";
const OUT = resolve(
  import.meta.dirname,
  "../migrations/20260809080000_seed-demo-co1.sql",
);

function sqlStr(v: string | null | undefined): string {
  if (v == null) return "NULL";
  return `'${String(v).replace(/'/g, "''")}'`;
}

function sqlNum(v: number | null | undefined): string {
  if (v == null) return "NULL";
  return String(v);
}

function sqlBool(v: boolean): string {
  return v ? "true" : "false";
}

function sqlDate(v: string | null | undefined): string {
  if (v == null) return "NULL";
  return sqlStr(v);
}

function sqlTs(v: string | null | undefined): string {
  if (v == null) return "NULL";
  return sqlStr(v);
}

function sqlTextArray(roles: string[]): string {
  return `ARRAY[${roles.map(sqlStr).join(", ")}]::text[]`;
}

type Row = Record<string, string>;

function insert(
  table: string,
  cols: string[],
  rows: Row[],
  conflict = "id",
): string {
  if (rows.length === 0) return `-- (no rows for ${table})\n`;
  const lines: string[] = [];
  lines.push(`INSERT INTO public.${table} (${cols.join(", ")})`);
  lines.push("VALUES");
  lines.push(
    rows
      .map((r, i) => {
        const vals = cols.map((c) => r[c] ?? "NULL").join(", ");
        const comma = i < rows.length - 1 ? "," : "";
        return `  (${vals})${comma}`;
      })
      .join("\n"),
  );
  lines.push(`ON CONFLICT (${conflict}) DO NOTHING;`);
  lines.push("");
  return lines.join("\n");
}

function section(title: string): string {
  return `\n-- ---------------------------------------------------------------------------\n-- ${title}\n-- ---------------------------------------------------------------------------\n\n`;
}

// --- Filter master data to co_1 / KW ---
const company = COMPANIES.find((c) => c.id === CO)!;
const branches = BRANCHES.filter((b) => b.companyId === CO);
const warehouses = WAREHOUSES.filter((w) => w.companyId === CO);
const warehouseIds = new Set(warehouses.map((w) => w.id));
const locations = LOCATIONS.filter((l) => warehouseIds.has(l.warehouseId));
const bankAccounts = BANK_ACCOUNTS.filter((b) => b.companyId === CO);
const taxCodes = TAX_CODES.filter((t) => t.jurisdiction === "KW");
const paymentTerms = PAYMENT_TERMS;
const customers = CUSTOMERS;
const suppliers = SUPPLIERS;
const products = PRODUCTS;
const fiscalPeriods = FISCAL_PERIODS.filter((f) => f.companyId === CO);
const accounts = ACCOUNTS;

const parts: string[] = [];

parts.push(`-- Demo seed: company co_1 (Atmata Trading Co., KW) only.
-- Generated by scripts/generate-demo-seed.ts from src/mocks/seed/*.
-- Preserves mock ids so UI / cross-document links stay intact.
-- Idempotent via ON CONFLICT DO NOTHING. Kuwait demo company only.
-- Skips auth-dependent rows that need real auth.users (approval_requests,
-- notifications). audit_events are seeded with "by" = NULL.

`);

// Companies
parts.push(section("companies"));
parts.push(
  insert(
    "companies",
    ["id", "name", "tax_profile", "base_currency", "vat_number", "status", "plan"],
    [
      {
        id: sqlStr(company.id),
        name: sqlStr(company.name),
        tax_profile: sqlStr(company.taxProfile),
        base_currency: sqlStr(company.baseCurrency),
        vat_number: sqlStr(company.vatNumber),
        status: sqlStr("active"),
        plan: sqlStr("pro"),
      },
    ],
  ),
);

// Currencies (needed for FX + USD bills)
parts.push(section("currencies"));
const currencyMeta: Record<string, { name: string; symbol: string; dp: number }> = {
  KWD: { name: "Kuwaiti Dinar", symbol: "د.ك", dp: 3 },
  SAR: { name: "Saudi Riyal", symbol: "ر.س", dp: 2 },
  AED: { name: "UAE Dirham", symbol: "د.إ", dp: 2 },
  USD: { name: "US Dollar", symbol: "$", dp: 2 },
};
parts.push(
  insert(
    "currencies",
    ["id", "company_id", "code", "name", "symbol", "decimal_places", "active"],
    Object.entries(currencyMeta).map(([code, m]) => ({
      id: sqlStr(`cur_${CO}_${code.toLowerCase()}`),
      company_id: sqlStr(CO),
      code: sqlStr(code),
      name: sqlStr(m.name),
      symbol: sqlStr(m.symbol),
      decimal_places: sqlNum(m.dp),
      active: sqlBool(true),
    })),
  ),
);

// Branches
parts.push(section("branches"));
parts.push(
  insert(
    "branches",
    ["id", "company_id", "name"],
    branches.map((b) => ({
      id: sqlStr(b.id),
      company_id: sqlStr(b.companyId),
      name: sqlStr(b.name),
    })),
  ),
);

// Warehouses
parts.push(section("warehouses"));
parts.push(
  insert(
    "warehouses",
    ["id", "company_id", "branch_id", "code", "name"],
    warehouses.map((w) => ({
      id: sqlStr(w.id),
      company_id: sqlStr(w.companyId),
      branch_id: sqlStr(branches[0]?.id ?? "br_1"),
      code: sqlStr(w.code),
      name: sqlStr(w.name),
    })),
  ),
);

// Locations
parts.push(section("locations"));
parts.push(
  insert(
    "locations",
    ["id", "company_id", "warehouse_id", "code", "name"],
    locations.map((l) => ({
      id: sqlStr(l.id),
      company_id: sqlStr(CO),
      warehouse_id: sqlStr(l.warehouseId),
      code: sqlStr(l.code),
      name: sqlStr(l.name),
    })),
  ),
);

// Tax codes (KW only)
parts.push(section("tax_codes (KW for co_1)"));
parts.push(
  insert(
    "tax_codes",
    [
      "id",
      "company_id",
      "jurisdiction",
      "code",
      "name_en",
      "name_ar",
      "rate",
      "is_input",
      "is_output",
    ],
    taxCodes.map((t) => ({
      id: sqlStr(t.id),
      company_id: sqlStr(CO),
      jurisdiction: sqlStr(t.jurisdiction),
      code: sqlStr(t.code),
      name_en: sqlStr(t.nameEn),
      name_ar: sqlStr(t.nameAr),
      rate: sqlNum(t.rate),
      is_input: sqlBool(t.isInput),
      is_output: sqlBool(t.isOutput),
    })),
  ),
);

// Payment terms
parts.push(section("payment_terms"));
parts.push(
  insert(
    "payment_terms",
    ["id", "company_id", "code", "name_en", "name_ar", "net_days"],
    paymentTerms.map((p) => ({
      id: sqlStr(p.id),
      company_id: sqlStr(CO),
      code: sqlStr(p.code),
      name_en: sqlStr(p.nameEn),
      name_ar: sqlStr(p.nameAr),
      net_days: sqlNum(p.netDays),
    })),
  ),
);

// Accounts (mock chart — different codes/ids than seed_company_defaults)
parts.push(section("accounts (mock chart of accounts)"));
parts.push(
  insert(
    "accounts",
    ["id", "company_id", "code", "name", "type", "active"],
    accounts.map((a) => ({
      id: sqlStr(a.id),
      company_id: sqlStr(CO),
      code: sqlStr(a.code),
      name: sqlStr(a.name),
      type: sqlStr(a.type),
      active: sqlBool(true),
    })),
  ),
);

// Minimal account mappings for posting engine
parts.push(section("account_mappings (mock account ids)"));
const mappingPairs: [string, string][] = [
  ["bank", "acc_bank_nbk_kwd"],
  ["accounts_receivable", "acc_ar"],
  ["accounts_payable", "acc_ap"],
  ["inventory", "acc_inv"],
  ["cogs", "acc_cogs"],
  ["revenue", "acc_revenue"],
  ["input_vat", "acc_input_vat"],
  ["output_vat", "acc_output_vat"],
  ["inventory_adjustment", "acc_inv_loss"],
  ["goods_received_not_invoiced", "acc_grir"],
];
parts.push(
  insert(
    "account_mappings",
    ["id", "company_id", "mapping_key", "account_id"],
    mappingPairs.map(([key, accountId]) => ({
      id: sqlStr(`map_${CO}_${key}`),
      company_id: sqlStr(CO),
      mapping_key: sqlStr(key),
      account_id: sqlStr(accountId),
    })),
  ),
);

// Bank accounts
parts.push(section("bank_accounts"));
parts.push(
  insert(
    "bank_accounts",
    ["id", "company_id", "name", "iban", "currency", "account_id", "active"],
    bankAccounts.map((b) => ({
      id: sqlStr(b.id),
      company_id: sqlStr(b.companyId),
      name: sqlStr(b.name),
      iban: sqlStr(b.iban),
      currency: sqlStr(b.currency),
      account_id: sqlStr("acc_bank_nbk_kwd"),
      active: sqlBool(true),
    })),
  ),
);

// Fiscal periods
parts.push(section("fiscal_periods"));
parts.push(
  insert(
    "fiscal_periods",
    ["id", "company_id", "year", "month", '"start"', '"end"', "status"],
    fiscalPeriods.map((f) => ({
      id: sqlStr(f.id),
      company_id: sqlStr(f.companyId),
      year: sqlNum(f.year),
      month: sqlNum(f.month),
      '"start"': sqlDate(f.start),
      '"end"': sqlDate(f.end),
      status: sqlStr(f.status),
    })),
  ),
);

// Products
parts.push(section("products"));
parts.push(
  insert(
    "products",
    [
      "id",
      "company_id",
      "sku",
      "name",
      "uom",
      "tax_code_id",
      "costing_method",
      "lot_tracked",
      "purchasable",
      "sellable",
      "default_purchase_price",
      "default_sale_price",
    ],
    products.map((p) => ({
      id: sqlStr(p.id),
      company_id: sqlStr(CO),
      sku: sqlStr(p.sku),
      name: sqlStr(p.name),
      uom: sqlStr(p.uom),
      tax_code_id: sqlStr(p.taxCodeId),
      costing_method: sqlStr(p.costingMethod),
      lot_tracked: sqlBool(p.lotTracked),
      purchasable: sqlBool(p.purchasable),
      sellable: sqlBool(p.sellable),
      default_purchase_price: sqlNum(p.defaultPurchasePrice),
      default_sale_price: sqlNum(p.defaultSalePrice),
    })),
  ),
);

// Customers
parts.push(section("customers"));
parts.push(
  insert(
    "customers",
    [
      "id",
      "company_id",
      "name",
      "vat_number",
      "credit_limit",
      "exposure",
      "payment_status",
      "credit_score",
      "active",
    ],
    customers.map((c) => ({
      id: sqlStr(c.id),
      company_id: sqlStr(CO),
      name: sqlStr(c.name),
      vat_number: sqlStr(c.vatNumber),
      credit_limit: sqlNum(c.creditLimit),
      exposure: sqlNum(c.exposure),
      payment_status: sqlStr(c.paymentStatus),
      credit_score: sqlStr(c.creditScore),
      active: sqlBool(true),
    })),
  ),
);

// Suppliers
parts.push(section("suppliers"));
parts.push(
  insert(
    "suppliers",
    [
      "id",
      "company_id",
      "name",
      "vat_number",
      "bank_account",
      "payment_term_id",
      "wht_applicable",
      "wht_rate",
      "active",
    ],
    suppliers.map((s) => ({
      id: sqlStr(s.id),
      company_id: sqlStr(CO),
      name: sqlStr(s.name),
      vat_number: sqlStr(s.vatNumber),
      bank_account: sqlStr(s.bankAccount),
      payment_term_id: sqlStr(s.paymentTermId),
      wht_applicable: sqlBool(s.whtApplicable ?? false),
      wht_rate: s.whtRate == null ? "NULL" : sqlNum(s.whtRate),
      active: sqlBool(true),
    })),
  ),
);

// FX rates for co_1 (all mock pairs — company-scoped)
parts.push(section("fx_rates"));
parts.push(
  insert(
    "fx_rates",
    [
      "id",
      "company_id",
      "base_currency",
      "quote_currency",
      "rate",
      "rate_date",
      "source",
    ],
    FX_RATES.map((r, i) => ({
      id: sqlStr(`fx_${CO}_${i + 1}`),
      company_id: sqlStr(CO),
      base_currency: sqlStr(r.from),
      quote_currency: sqlStr(r.to),
      rate: sqlNum(r.rate),
      rate_date: sqlDate(r.date),
      source: sqlStr("manual"),
    })),
  ),
);

// Approval rules
parts.push(section("approval_rules"));
const rulesByDoc = new Map<string, typeof APPROVAL_RULES>();
for (const r of APPROVAL_RULES) {
  const list = rulesByDoc.get(r.docType) ?? [];
  list.push(r);
  rulesByDoc.set(r.docType, list);
}
const approvalRows: Row[] = [];
for (const [, rules] of rulesByDoc) {
  const sorted = [...rules].sort((a, b) => a.minAmount - b.minAmount);
  sorted.forEach((r, idx) => {
    approvalRows.push({
      id: sqlStr(r.id),
      company_id: sqlStr(CO),
      doc_type: sqlStr(r.docType),
      min_amount: sqlNum(r.minAmount),
      max_amount: "NULL",
      // Trigger requires approver_roles ∩ {approver,admin} nonempty.
      approver_roles: sqlTextArray(
        r.approverRole === "approver" || r.approverRole === "admin"
          ? [r.approverRole]
          : ["approver", r.approverRole],
      ),
      sequence: sqlNum(idx + 1),
      active: sqlBool(true),
    });
  });
}
parts.push(
  insert(
    "approval_rules",
    [
      "id",
      "company_id",
      "doc_type",
      "min_amount",
      "max_amount",
      "approver_roles",
      "sequence",
      "active",
    ],
    approvalRows,
  ),
);

// Document sequences — next_number past highest demo doc
parts.push(section("document_sequences"));
const sequences: { docType: string; prefix: string; padding: number; next: number }[] =
  [
    { docType: "pr", prefix: "PR", padding: 5, next: 2 },
    { docType: "rfq", prefix: "RFQ", padding: 5, next: 2 },
    { docType: "po", prefix: "PO", padding: 5, next: 6 },
    { docType: "grn", prefix: "GRN", padding: 5, next: 3 },
    { docType: "vendor_bill", prefix: "BILL", padding: 5, next: 5 },
    { docType: "vendor_payment", prefix: "VPAY", padding: 5, next: 2 },
    { docType: "debit_note", prefix: "DN", padding: 5, next: 2 },
    { docType: "vendor_return", prefix: "VR", padding: 5, next: 2 },
    { docType: "opportunity", prefix: "OPP", padding: 5, next: 3 },
    { docType: "quote", prefix: "QT", padding: 5, next: 5 },
    { docType: "so", prefix: "SO", padding: 5, next: 3 },
    { docType: "dn", prefix: "DEL", padding: 5, next: 2 },
    { docType: "customer_invoice", prefix: "INV", padding: 5, next: 2 },
    { docType: "customer_receipt", prefix: "RCP", padding: 5, next: 2 },
    { docType: "credit_note", prefix: "CN", padding: 5, next: 2 },
    { docType: "customer_return", prefix: "CR", padding: 5, next: 2 },
    { docType: "journal_entry", prefix: "JE", padding: 5, next: 9 },
    { docType: "stock_move", prefix: "SM", padding: 6, next: 7 },
    { docType: "stock_adjustment", prefix: "ADJ", padding: 5, next: 2 },
    { docType: "internal_transfer", prefix: "TRX", padding: 5, next: 2 },
  ];
parts.push(
  insert(
    "document_sequences",
    ["id", "company_id", "doc_type", "prefix", "year", "padding", "next_number"],
    sequences.map((s) => ({
      id: sqlStr(`seq_${CO}_${s.docType}_2026`),
      company_id: sqlStr(CO),
      doc_type: sqlStr(s.docType),
      prefix: sqlStr(s.prefix),
      year: sqlNum(2026),
      padding: sqlNum(s.padding),
      next_number: sqlNum(s.next),
    })),
  ),
);

// P2P — purchase requisitions
parts.push(section("purchase_requisitions + lines"));
parts.push(
  insert(
    "purchase_requisitions",
    [
      "id",
      "company_id",
      "number",
      "requested_by",
      "date",
      "needed_by",
      "state",
      "notes",
    ],
    PURCHASE_REQUISITIONS.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      requested_by: sqlStr(d.requestedBy),
      date: sqlDate(d.date),
      needed_by: sqlDate(d.neededBy),
      state: sqlStr(d.state),
      notes: d.notes == null ? "NULL" : sqlStr(d.notes),
    })),
  ),
);
parts.push(
  insert(
    "purchase_requisition_lines",
    [
      "id",
      "company_id",
      "purchase_requisition_id",
      "product_id",
      "description",
      "qty",
      "unit_price",
      "tax_code_id",
    ],
    PURCHASE_REQUISITIONS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.lines.map((l) => ({
        id: sqlStr(l.id),
        company_id: sqlStr(d.companyId),
        purchase_requisition_id: sqlStr(d.id),
        product_id: sqlStr(l.productId),
        description: sqlStr(l.description),
        qty: sqlNum(l.qty),
        unit_price: sqlNum(l.unitPrice),
        tax_code_id: sqlStr(l.taxCodeId),
      })),
    ),
  ),
);

// RFQ
parts.push(section("rfqs + children (award FKs filled after quotes + POs)"));
parts.push(
  insert(
    "rfqs",
    [
      "id",
      "company_id",
      "number",
      "date",
      "expected_quote_by",
      "state",
      "awarded_vendor_id",
      "awarded_quote_id",
      "award_po_id",
      "awarded_at",
      "awarded_by",
      "notes",
    ],
    RFQS.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      date: sqlDate(d.date),
      expected_quote_by: sqlDate(d.expectedQuoteBy),
      state: sqlStr(d.state),
      // awarded_vendor_id OK (suppliers already seeded); quote/po FKs deferred
      awarded_vendor_id: d.award ? sqlStr(d.award.vendorId) : "NULL",
      awarded_quote_id: "NULL",
      award_po_id: "NULL",
      awarded_at: d.award ? sqlTs(d.award.awardedAt) : "NULL",
      awarded_by: d.award ? sqlStr(d.award.awardedBy) : "NULL",
      notes: d.notes == null ? "NULL" : sqlStr(d.notes),
    })),
  ),
);
parts.push(
  insert(
    "rfq_sources",
    ["id", "company_id", "rfq_id", "purchase_requisition_id"],
    RFQS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.prIds.map((prId, i) => ({
        id: sqlStr(`${d.id}_src_${i + 1}`),
        company_id: sqlStr(d.companyId),
        rfq_id: sqlStr(d.id),
        purchase_requisition_id: sqlStr(prId),
      })),
    ),
  ),
);
parts.push(
  insert(
    "rfq_invited_suppliers",
    ["id", "company_id", "rfq_id", "supplier_id", "sent_at"],
    RFQS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.invitedVendorIds.map((supId, i) => ({
        id: sqlStr(`${d.id}_inv_${i + 1}`),
        company_id: sqlStr(d.companyId),
        rfq_id: sqlStr(d.id),
        supplier_id: sqlStr(supId),
        sent_at: sqlTs(`${d.date}T09:00:00Z`),
      })),
    ),
  ),
);
parts.push(
  insert(
    "rfq_lines",
    ["id", "company_id", "rfq_id", "product_id", "description", "qty"],
    RFQS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.lines.map((l) => ({
        id: sqlStr(l.id),
        company_id: sqlStr(d.companyId),
        rfq_id: sqlStr(d.id),
        product_id: sqlStr(l.productId),
        description: sqlStr(l.description),
        qty: sqlNum(l.qty),
      })),
    ),
  ),
);
parts.push(
  insert(
    "rfq_quotes",
    [
      "id",
      "company_id",
      "rfq_id",
      "vendor_id",
      "received_date",
      "currency",
      "total",
      "valid_until",
    ],
    RFQS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.quotes.map((q) => ({
        id: sqlStr(q.id),
        company_id: sqlStr(d.companyId),
        rfq_id: sqlStr(d.id),
        vendor_id: sqlStr(q.vendorId),
        received_date: sqlDate(q.receivedDate),
        currency: sqlStr(q.currency),
        total: sqlNum(q.total),
        valid_until: sqlDate(q.validUntil),
      })),
    ),
  ),
);
parts.push(
  insert(
    "rfq_quote_lines",
    [
      "id",
      "company_id",
      "rfq_quote_id",
      "rfq_line_id",
      "unit_price",
      "lead_time_days",
      "notes",
    ],
    RFQS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.quotes.flatMap((q) =>
        q.lineQuotes.map((lq, i) => ({
          id: sqlStr(`${q.id}_l${i + 1}`),
          company_id: sqlStr(d.companyId),
          rfq_quote_id: sqlStr(q.id),
          rfq_line_id: sqlStr(lq.rfqLineId),
          unit_price: sqlNum(lq.unitPrice),
          lead_time_days: sqlNum(lq.leadTimeDays),
          notes: lq.notes == null ? "NULL" : sqlStr(lq.notes),
        })),
      ),
    ),
  ),
);

// Purchase orders — note: award_po_id FK may reference po before insert if RFQ
// already has award_po_id. RFQs table has award_po_id as plain text FK?
// Check: rfqs.award_po_id — need FK?
parts.push(section("purchase_orders + lines"));
parts.push(
  insert(
    "purchase_orders",
    [
      "id",
      "company_id",
      "number",
      "supplier_id",
      "pr_id",
      "date",
      "expected_date",
      "currency",
      "payment_term_id",
      "warehouse_id",
      "state",
      "subtotal",
      "tax_total",
      "total",
      "notes",
    ],
    PURCHASE_ORDERS.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      supplier_id: sqlStr(d.supplierId),
      pr_id: d.prId ? sqlStr(d.prId) : "NULL",
      date: sqlDate(d.date),
      expected_date: sqlDate(d.expectedDate),
      currency: sqlStr(d.currency),
      payment_term_id: sqlStr(d.paymentTermId),
      warehouse_id: sqlStr(d.warehouseId),
      state: sqlStr(d.state),
      subtotal: sqlNum(d.subtotal),
      tax_total: sqlNum(d.taxTotal),
      total: sqlNum(d.total),
      notes: d.notes == null ? "NULL" : sqlStr(d.notes),
    })),
  ),
);
parts.push(
  insert(
    "purchase_order_lines",
    [
      "id",
      "company_id",
      "purchase_order_id",
      "product_id",
      "description",
      "qty",
      "unit_price",
      "tax_code_id",
    ],
    PURCHASE_ORDERS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.lines.map((l) => ({
        id: sqlStr(l.id),
        company_id: sqlStr(d.companyId),
        purchase_order_id: sqlStr(d.id),
        product_id: sqlStr(l.productId),
        description: sqlStr(l.description),
        qty: sqlNum(l.qty),
        unit_price: sqlNum(l.unitPrice),
        tax_code_id: sqlStr(l.taxCodeId),
      })),
    ),
  ),
);

// RFQ award FKs: awarded_quote_id → rfq_quotes, award_po_id → purchase_orders
for (const d of RFQS.filter((x) => x.companyId === CO && x.award)) {
  parts.push(
    `UPDATE public.rfqs
SET awarded_quote_id = ${sqlStr(d.award!.quoteId)},
    award_po_id = ${d.award!.poId ? sqlStr(d.award!.poId) : "NULL"}
WHERE company_id = ${sqlStr(CO)} AND id = ${sqlStr(d.id)}
  AND awarded_quote_id IS NULL;\n\n`,
  );
}

parts.push(section("goods_receipts + lines"));
parts.push(
  insert(
    "goods_receipts",
    [
      "id",
      "company_id",
      "number",
      "po_id",
      "supplier_id",
      "warehouse_id",
      "date",
      "state",
      "notes",
    ],
    GOODS_RECEIPTS.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      po_id: sqlStr(d.poId),
      supplier_id: sqlStr(d.supplierId),
      warehouse_id: sqlStr(d.warehouseId),
      date: sqlDate(d.date),
      state: sqlStr(d.state),
      notes: "NULL",
    })),
  ),
);
parts.push(
  insert(
    "goods_receipt_lines",
    [
      "id",
      "company_id",
      "goods_receipt_id",
      "po_line_id",
      "product_id",
      "description",
      "qty",
      "unit_price",
      "tax_code_id",
      "qty_received",
    ],
    GOODS_RECEIPTS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.lines.map((l) => ({
        id: sqlStr(l.id),
        company_id: sqlStr(d.companyId),
        goods_receipt_id: sqlStr(d.id),
        po_line_id: sqlStr(l.poLineId),
        product_id: sqlStr(l.productId),
        description: sqlStr(l.description),
        qty: sqlNum(l.qty),
        unit_price: sqlNum(l.unitPrice),
        tax_code_id: sqlStr(l.taxCodeId),
        qty_received: sqlNum(l.qtyReceived),
      })),
    ),
  ),
);

parts.push(section("vendor_bills + lines"));
// Schema UNIQUE (company_id, supplier_id, invoice_number) blocks mock bill_4,
// which intentionally reuses bill_1's vendor invoice number for the duplicate demo.
const vendorBillsSeedable = VENDOR_BILLS.filter(
  (d) => d.companyId === CO && d.id !== "bill_4",
);
parts.push(
  insert(
    "vendor_bills",
    [
      "id",
      "company_id",
      "number",
      "supplier_id",
      "po_id",
      "grn_id",
      "invoice_number",
      "date",
      "due_date",
      "currency",
      "state",
      "subtotal",
      "tax_total",
      "total",
      "paid",
      "three_way_match",
      "discrepancy_reason",
    ],
    vendorBillsSeedable.map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      supplier_id: sqlStr(d.supplierId),
      po_id: d.poId ? sqlStr(d.poId) : "NULL",
      grn_id: d.grnId ? sqlStr(d.grnId) : "NULL",
      invoice_number: sqlStr(d.invoiceNumber),
      date: sqlDate(d.date),
      due_date: sqlDate(d.dueDate),
      currency: sqlStr(d.currency),
      state: sqlStr(d.state),
      subtotal: sqlNum(d.subtotal),
      tax_total: sqlNum(d.taxTotal),
      total: sqlNum(d.total),
      paid: sqlNum(d.paid),
      three_way_match: sqlStr(d.threeWayMatch),
      discrepancy_reason:
        d.discrepancyReason == null ? "NULL" : sqlStr(d.discrepancyReason),
    })),
  ),
);
parts.push(
  insert(
    "vendor_bill_lines",
    [
      "id",
      "company_id",
      "vendor_bill_id",
      "po_line_id",
      "grn_line_id",
      "product_id",
      "description",
      "qty",
      "unit_price",
      "tax_code_id",
    ],
    vendorBillsSeedable.flatMap((d) =>
      d.lines.map((l) => ({
        id: sqlStr(l.id),
        company_id: sqlStr(d.companyId),
        vendor_bill_id: sqlStr(d.id),
        po_line_id: l.poLineId ? sqlStr(l.poLineId) : "NULL",
        grn_line_id: l.grnLineId ? sqlStr(l.grnLineId) : "NULL",
        product_id: sqlStr(l.productId),
        description: sqlStr(l.description),
        qty: sqlNum(l.qty),
        unit_price: sqlNum(l.unitPrice),
        tax_code_id: sqlStr(l.taxCodeId),
      })),
    ),
  ),
);

parts.push(section("vendor_payments + allocations"));
parts.push(
  insert(
    "vendor_payments",
    [
      "id",
      "company_id",
      "number",
      "supplier_id",
      "bank_account_id",
      "date",
      "currency",
      "state",
      "amount",
      "method",
    ],
    VENDOR_PAYMENTS.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      supplier_id: sqlStr(d.supplierId),
      bank_account_id: sqlStr(d.bankAccountId),
      date: sqlDate(d.date),
      currency: sqlStr(d.currency),
      state: sqlStr(d.state),
      amount: sqlNum(d.amount),
      method: sqlStr(d.method),
    })),
  ),
);
parts.push(
  insert(
    "vendor_payment_allocations",
    ["id", "company_id", "vendor_payment_id", "bill_id", "amount"],
    VENDOR_PAYMENTS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.allocations.map((a, i) => ({
        id: sqlStr(`${d.id}_a${i + 1}`),
        company_id: sqlStr(d.companyId),
        vendor_payment_id: sqlStr(d.id),
        bill_id: sqlStr(a.billId),
        amount: sqlNum(a.amount),
      })),
    ),
  ),
);

// Vendor returns first without debit_note_id, then debit notes, then update
parts.push(section("vendor_returns + lines (debit_note_id linked after)"));
parts.push(
  insert(
    "vendor_returns",
    [
      "id",
      "company_id",
      "number",
      "grn_id",
      "supplier_id",
      "warehouse_id",
      "date",
      "state",
      "debit_note_id",
      "notes",
    ],
    VENDOR_RETURNS.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      grn_id: sqlStr(d.grnId),
      supplier_id: sqlStr(d.supplierId),
      warehouse_id: sqlStr(d.warehouseId),
      date: sqlDate(d.date),
      state: sqlStr(d.state),
      debit_note_id: "NULL",
      notes: d.notes == null ? "NULL" : sqlStr(d.notes),
    })),
  ),
);
parts.push(
  insert(
    "vendor_return_lines",
    [
      "id",
      "company_id",
      "vendor_return_id",
      "grn_line_id",
      "product_id",
      "description",
      "qty",
      "unit_price",
      "tax_code_id",
      "reason_code",
      "notes",
    ],
    VENDOR_RETURNS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.lines.map((l) => ({
        id: sqlStr(l.id),
        company_id: sqlStr(d.companyId),
        vendor_return_id: sqlStr(d.id),
        grn_line_id: sqlStr(l.grnLineId),
        product_id: sqlStr(l.productId),
        description: sqlStr(l.description),
        qty: sqlNum(l.qty),
        unit_price: sqlNum(l.unitPrice),
        tax_code_id: sqlStr(l.taxCodeId),
        reason_code: sqlStr(l.reasonCode),
        notes: l.notes == null ? "NULL" : sqlStr(l.notes),
      })),
    ),
  ),
);

parts.push(section("debit_notes"));
parts.push(
  insert(
    "debit_notes",
    [
      "id",
      "company_id",
      "number",
      "supplier_id",
      "vendor_return_id",
      "bill_id",
      "date",
      "currency",
      "state",
      "subtotal",
      "tax_total",
      "total",
      "settled",
    ],
    DEBIT_NOTES.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      supplier_id: sqlStr(d.supplierId),
      vendor_return_id: sqlStr(d.vendorReturnId),
      bill_id: d.billId ? sqlStr(d.billId) : "NULL",
      date: sqlDate(d.date),
      currency: sqlStr(d.currency),
      state: sqlStr(d.state),
      subtotal: sqlNum(d.subtotal),
      tax_total: sqlNum(d.taxTotal),
      total: sqlNum(d.total),
      settled: sqlNum(d.settled),
    })),
  ),
);
for (const d of VENDOR_RETURNS.filter((x) => x.companyId === CO && x.debitNoteId)) {
  parts.push(
    `UPDATE public.vendor_returns\nSET debit_note_id = ${sqlStr(d.debitNoteId)}\nWHERE company_id = ${sqlStr(CO)} AND id = ${sqlStr(d.id)} AND debit_note_id IS NULL;\n\n`,
  );
}

// Q2C
parts.push(section("opportunities"));
parts.push(
  insert(
    "opportunities",
    [
      "id",
      "company_id",
      "number",
      "customer_id",
      "title",
      "stage",
      "value",
      "probability",
      "next_action",
      "days_idle",
    ],
    OPPORTUNITIES.map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(CO),
      number: sqlStr(d.number),
      customer_id: sqlStr(d.customerId),
      title: sqlStr(d.title),
      stage: sqlStr(d.stage),
      value: sqlNum(d.value),
      probability: sqlNum(d.probability),
      next_action: d.nextAction == null ? "NULL" : sqlStr(d.nextAction),
      days_idle: sqlNum(d.daysIdle),
    })),
  ),
);

parts.push(section("quotes + lines"));
parts.push(
  insert(
    "quotes",
    [
      "id",
      "company_id",
      "number",
      "customer_id",
      "opportunity_id",
      "date",
      "valid_until",
      "currency",
      "state",
      "subtotal",
      "tax_total",
      "total",
      "notes",
    ],
    QUOTES.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      customer_id: sqlStr(d.customerId),
      opportunity_id: d.opportunityId ? sqlStr(d.opportunityId) : "NULL",
      date: sqlDate(d.date),
      valid_until: sqlDate(d.validUntil),
      currency: sqlStr(d.currency),
      state: sqlStr(d.state),
      subtotal: sqlNum(d.subtotal),
      tax_total: sqlNum(d.taxTotal),
      total: sqlNum(d.total),
      notes: "NULL",
    })),
  ),
);
parts.push(
  insert(
    "quote_lines",
    [
      "id",
      "company_id",
      "quote_id",
      "product_id",
      "description",
      "qty",
      "unit_price",
      "tax_code_id",
    ],
    QUOTES.filter((d) => d.companyId === CO).flatMap((d) =>
      d.lines.map((l) => ({
        id: sqlStr(l.id),
        company_id: sqlStr(d.companyId),
        quote_id: sqlStr(d.id),
        product_id: sqlStr(l.productId),
        description: sqlStr(l.description),
        qty: sqlNum(l.qty),
        unit_price: sqlNum(l.unitPrice),
        tax_code_id: sqlStr(l.taxCodeId),
      })),
    ),
  ),
);

parts.push(section("sales_orders + lines"));
parts.push(
  insert(
    "sales_orders",
    [
      "id",
      "company_id",
      "number",
      "customer_id",
      "quote_id",
      "date",
      "expected_delivery_date",
      "currency",
      "warehouse_id",
      "state",
      "blocked_reason",
      "exceptional",
      "subtotal",
      "tax_total",
      "total",
    ],
    SALES_ORDERS.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      customer_id: sqlStr(d.customerId),
      quote_id: d.quoteId ? sqlStr(d.quoteId) : "NULL",
      date: sqlDate(d.date),
      expected_delivery_date: sqlDate(d.expectedDeliveryDate),
      currency: sqlStr(d.currency),
      warehouse_id: sqlStr(d.warehouseId),
      state: sqlStr(d.state),
      blocked_reason: d.blockedReason == null ? "NULL" : sqlStr(d.blockedReason),
      exceptional: sqlBool(d.exceptional),
      subtotal: sqlNum(d.subtotal),
      tax_total: sqlNum(d.taxTotal),
      total: sqlNum(d.total),
    })),
  ),
);
parts.push(
  insert(
    "sales_order_lines",
    [
      "id",
      "company_id",
      "sales_order_id",
      "product_id",
      "description",
      "qty",
      "unit_price",
      "tax_code_id",
    ],
    SALES_ORDERS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.lines.map((l) => ({
        id: sqlStr(l.id),
        company_id: sqlStr(d.companyId),
        sales_order_id: sqlStr(d.id),
        product_id: sqlStr(l.productId),
        description: sqlStr(l.description),
        qty: sqlNum(l.qty),
        unit_price: sqlNum(l.unitPrice),
        tax_code_id: sqlStr(l.taxCodeId),
      })),
    ),
  ),
);

parts.push(section("delivery_notes + lines"));
parts.push(
  insert(
    "delivery_notes",
    [
      "id",
      "company_id",
      "number",
      "so_id",
      "customer_id",
      "warehouse_id",
      "date",
      "state",
    ],
    DELIVERY_NOTES.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      so_id: sqlStr(d.soId),
      customer_id: sqlStr(d.customerId),
      warehouse_id: sqlStr(d.warehouseId),
      date: sqlDate(d.date),
      state: sqlStr(d.state),
    })),
  ),
);
parts.push(
  insert(
    "delivery_note_lines",
    [
      "id",
      "company_id",
      "delivery_note_id",
      "so_line_id",
      "product_id",
      "description",
      "qty",
      "unit_price",
      "tax_code_id",
      "qty_delivered",
    ],
    DELIVERY_NOTES.filter((d) => d.companyId === CO).flatMap((d) =>
      d.lines.map((l) => ({
        id: sqlStr(l.id),
        company_id: sqlStr(d.companyId),
        delivery_note_id: sqlStr(d.id),
        so_line_id: sqlStr(l.soLineId),
        product_id: sqlStr(l.productId),
        description: sqlStr(l.description),
        qty: sqlNum(l.qty),
        unit_price: sqlNum(l.unitPrice),
        tax_code_id: sqlStr(l.taxCodeId),
        qty_delivered: sqlNum(l.qtyDelivered),
      })),
    ),
  ),
);

parts.push(section("customer_invoices + lines"));
parts.push(
  insert(
    "customer_invoices",
    [
      "id",
      "company_id",
      "number",
      "customer_id",
      "so_id",
      "dn_id",
      "date",
      "due_date",
      "currency",
      "state",
      "subtotal",
      "tax_total",
      "total",
      "paid",
    ],
    CUSTOMER_INVOICES.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      customer_id: sqlStr(d.customerId),
      so_id: d.soId ? sqlStr(d.soId) : "NULL",
      dn_id: d.dnId ? sqlStr(d.dnId) : "NULL",
      date: sqlDate(d.date),
      due_date: sqlDate(d.dueDate),
      currency: sqlStr(d.currency),
      state: sqlStr(d.state),
      subtotal: sqlNum(d.subtotal),
      tax_total: sqlNum(d.taxTotal),
      total: sqlNum(d.total),
      paid: sqlNum(d.paid),
    })),
  ),
);
parts.push(
  insert(
    "customer_invoice_lines",
    [
      "id",
      "company_id",
      "customer_invoice_id",
      "so_line_id",
      "dn_line_id",
      "product_id",
      "description",
      "qty",
      "unit_price",
      "tax_code_id",
    ],
    CUSTOMER_INVOICES.filter((d) => d.companyId === CO).flatMap((d) =>
      d.lines.map((l) => ({
        id: sqlStr(l.id),
        company_id: sqlStr(d.companyId),
        customer_invoice_id: sqlStr(d.id),
        so_line_id: l.soLineId ? sqlStr(l.soLineId) : "NULL",
        dn_line_id: l.dnLineId ? sqlStr(l.dnLineId) : "NULL",
        product_id: sqlStr(l.productId),
        description: sqlStr(l.description),
        qty: sqlNum(l.qty),
        unit_price: sqlNum(l.unitPrice),
        tax_code_id: sqlStr(l.taxCodeId),
      })),
    ),
  ),
);

parts.push(section("customer_receipts + allocations"));
parts.push(
  insert(
    "customer_receipts",
    [
      "id",
      "company_id",
      "number",
      "customer_id",
      "bank_account_id",
      "date",
      "currency",
      "state",
      "amount",
      "method",
    ],
    CUSTOMER_RECEIPTS.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      customer_id: sqlStr(d.customerId),
      bank_account_id: sqlStr(d.bankAccountId),
      date: sqlDate(d.date),
      currency: sqlStr(d.currency),
      state: sqlStr(d.state),
      amount: sqlNum(d.amount),
      method: sqlStr(d.method),
    })),
  ),
);
parts.push(
  insert(
    "customer_receipt_allocations",
    ["id", "company_id", "customer_receipt_id", "invoice_id", "amount"],
    CUSTOMER_RECEIPTS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.allocations.map((a, i) => ({
        id: sqlStr(`${d.id}_a${i + 1}`),
        company_id: sqlStr(d.companyId),
        customer_receipt_id: sqlStr(d.id),
        invoice_id: sqlStr(a.invoiceId),
        amount: sqlNum(a.amount),
      })),
    ),
  ),
);

parts.push(section("customer_returns + lines (credit_note_id linked after)"));
parts.push(
  insert(
    "customer_returns",
    [
      "id",
      "company_id",
      "number",
      "dn_id",
      "customer_id",
      "warehouse_id",
      "date",
      "state",
      "credit_note_id",
      "notes",
    ],
    CUSTOMER_RETURNS.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      dn_id: sqlStr(d.dnId),
      customer_id: sqlStr(d.customerId),
      warehouse_id: sqlStr(d.warehouseId),
      date: sqlDate(d.date),
      state: sqlStr(d.state),
      credit_note_id: "NULL",
      notes: d.notes == null ? "NULL" : sqlStr(d.notes),
    })),
  ),
);
parts.push(
  insert(
    "customer_return_lines",
    [
      "id",
      "company_id",
      "customer_return_id",
      "dn_line_id",
      "product_id",
      "description",
      "qty",
      "unit_price",
      "tax_code_id",
      "reason_code",
      "lot_number",
    ],
    CUSTOMER_RETURNS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.lines.map((l) => ({
        id: sqlStr(l.id),
        company_id: sqlStr(d.companyId),
        customer_return_id: sqlStr(d.id),
        dn_line_id: sqlStr(l.dnLineId),
        product_id: sqlStr(l.productId),
        description: sqlStr(l.description),
        qty: sqlNum(l.qty),
        unit_price: sqlNum(l.unitPrice),
        tax_code_id: sqlStr(l.taxCodeId),
        reason_code: sqlStr(l.reasonCode),
        lot_number: l.lotNumber == null ? "NULL" : sqlStr(l.lotNumber),
      })),
    ),
  ),
);

parts.push(section("credit_notes"));
parts.push(
  insert(
    "credit_notes",
    [
      "id",
      "company_id",
      "number",
      "customer_id",
      "customer_return_id",
      "invoice_id",
      "date",
      "currency",
      "state",
      "subtotal",
      "tax_total",
      "total",
      "applied",
    ],
    CREDIT_NOTES.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      customer_id: sqlStr(d.customerId),
      customer_return_id: sqlStr(d.customerReturnId),
      invoice_id: d.invoiceId ? sqlStr(d.invoiceId) : "NULL",
      date: sqlDate(d.date),
      currency: sqlStr(d.currency),
      state: sqlStr(d.state),
      subtotal: sqlNum(d.subtotal),
      tax_total: sqlNum(d.taxTotal),
      total: sqlNum(d.total),
      applied: sqlNum(d.applied),
    })),
  ),
);
for (const d of CUSTOMER_RETURNS.filter(
  (x) => x.companyId === CO && x.creditNoteId,
)) {
  parts.push(
    `UPDATE public.customer_returns\nSET credit_note_id = ${sqlStr(d.creditNoteId)}\nWHERE company_id = ${sqlStr(CO)} AND id = ${sqlStr(d.id)} AND credit_note_id IS NULL;\n\n`,
  );
}

// GL
parts.push(section("journal_entries + lines"));
parts.push(
  insert(
    "journal_entries",
    [
      "id",
      "company_id",
      "number",
      "date",
      "currency",
      "state",
      "source_type",
      "source_id",
      "description",
    ],
    JOURNAL_ENTRIES.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      date: sqlDate(d.date),
      currency: sqlStr(d.currency),
      state: sqlStr(d.state),
      source_type: d.sourceType ? sqlStr(d.sourceType) : "NULL",
      source_id: d.sourceId ? sqlStr(d.sourceId) : "NULL",
      description: sqlStr(d.description),
    })),
  ),
);
parts.push(
  insert(
    "journal_entry_lines",
    [
      "id",
      "company_id",
      "journal_entry_id",
      "account_id",
      "description",
      "debit",
      "credit",
    ],
    JOURNAL_ENTRIES.filter((d) => d.companyId === CO).flatMap((d) =>
      d.lines.map((l) => ({
        id: sqlStr(l.id),
        company_id: sqlStr(d.companyId),
        journal_entry_id: sqlStr(d.id),
        account_id: sqlStr(l.accountId),
        description: sqlStr(l.description),
        debit: sqlNum(l.debit),
        credit: sqlNum(l.credit),
      })),
    ),
  ),
);

// Inventory
parts.push(section("internal_transfers + lines"));
parts.push(
  insert(
    "internal_transfers",
    [
      "id",
      "company_id",
      "number",
      "from_warehouse_id",
      "to_warehouse_id",
      "date",
      "state",
      "notes",
    ],
    INTERNAL_TRANSFERS.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      from_warehouse_id: sqlStr(d.fromWarehouseId),
      to_warehouse_id: sqlStr(d.toWarehouseId),
      date: sqlDate(d.date),
      state: sqlStr(d.state),
      notes: d.notes == null ? "NULL" : sqlStr(d.notes),
    })),
  ),
);
parts.push(
  insert(
    "internal_transfer_lines",
    [
      "id",
      "company_id",
      "internal_transfer_id",
      "product_id",
      "qty",
      "lot_number",
    ],
    INTERNAL_TRANSFERS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.lines.map((l) => ({
        id: sqlStr(l.id),
        company_id: sqlStr(d.companyId),
        internal_transfer_id: sqlStr(d.id),
        product_id: sqlStr(l.productId),
        qty: sqlNum(l.qty),
        lot_number: l.lotNumber == null ? "NULL" : sqlStr(l.lotNumber),
      })),
    ),
  ),
);

parts.push(section("stock_adjustments + lines"));
parts.push(
  insert(
    "stock_adjustments",
    ["id", "company_id", "number", "date", "state", "approved_by", "notes"],
    STOCK_ADJUSTMENTS.filter((d) => d.companyId === CO).map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(d.companyId),
      number: sqlStr(d.number),
      date: sqlDate(d.date),
      state: sqlStr(d.state),
      approved_by: d.approvedBy == null ? "NULL" : sqlStr(d.approvedBy),
      notes: d.notes == null ? "NULL" : sqlStr(d.notes),
    })),
  ),
);
parts.push(
  insert(
    "stock_adjustment_lines",
    [
      "id",
      "company_id",
      "stock_adjustment_id",
      "product_id",
      "warehouse_id",
      "qty_delta",
      "reason",
    ],
    STOCK_ADJUSTMENTS.filter((d) => d.companyId === CO).flatMap((d) =>
      d.lines.map((l) => ({
        id: sqlStr(l.id),
        company_id: sqlStr(d.companyId),
        stock_adjustment_id: sqlStr(d.id),
        product_id: sqlStr(l.productId),
        warehouse_id: sqlStr(l.warehouseId),
        qty_delta: sqlNum(l.qtyDelta),
        reason: sqlStr(l.reason),
      })),
    ),
  ),
);

parts.push(section("stock_moves"));
parts.push(
  insert(
    "stock_moves",
    [
      "id",
      "company_id",
      "number",
      "date",
      "product_id",
      "warehouse_id",
      "direction",
      "qty",
      "cost_per_unit",
      "lot_number",
      "source_type",
      "source_id",
    ],
    STOCK_MOVES.map((d) => ({
      id: sqlStr(d.id),
      company_id: sqlStr(CO),
      number: sqlStr(d.number),
      date: sqlDate(d.date),
      product_id: sqlStr(d.productId),
      warehouse_id: sqlStr(d.warehouseId),
      direction: sqlStr(d.direction),
      qty: sqlNum(d.qty),
      cost_per_unit: sqlNum(d.costPerUnit),
      lot_number: d.lotNumber == null ? "NULL" : sqlStr(d.lotNumber),
      source_type: sqlStr(d.sourceType),
      source_id: sqlStr(d.sourceId),
    })),
  ),
);

// Inventory lot referenced by DN / transfer (not a FEFO engine — just the mock lot)
parts.push(section("inventory_lots (mock lot DC-2026-Q2 only)"));
parts.push(
  insert(
    "inventory_lots",
    [
      "id",
      "company_id",
      "product_id",
      "warehouse_id",
      "lot_number",
      "received_on",
      "on_hand",
      "status",
    ],
    [
      {
        id: sqlStr("lot_dc_2026_q2_wh1"),
        company_id: sqlStr(CO),
        product_id: sqlStr("prod_4"),
        warehouse_id: sqlStr("wh_1"),
        lot_number: sqlStr("DC-2026-Q2"),
        received_on: sqlDate("2026-04-01"),
        on_hand: sqlNum(0),
        status: sqlStr("depleted"),
      },
      {
        id: sqlStr("lot_dc_2026_q2_wh2"),
        company_id: sqlStr(CO),
        product_id: sqlStr("prod_4"),
        warehouse_id: sqlStr("wh_2"),
        lot_number: sqlStr("DC-2026-Q2"),
        received_on: sqlDate("2026-04-10"),
        // transfer 4 in, deliver 2 out, return 1 in → ~3 (illustrative)
        on_hand: sqlNum(3),
        status: sqlStr("active"),
      },
    ],
  ),
);

// Audit events with by = NULL (auth.users FK)
parts.push(section('audit_events ("by" left NULL — no fake auth.users)'));
parts.push(
  insert(
    "audit_events",
    [
      "id",
      "company_id",
      "doc_id",
      "doc_type",
      "from_state",
      "to_state",
      '"by"',
      "reason",
      "at",
    ],
    AUDIT_EVENTS.map((e) => ({
      id: sqlStr(e.id),
      company_id: sqlStr(CO),
      doc_id: sqlStr(e.docId),
      doc_type: sqlStr(e.docType),
      from_state: e.fromState == null ? "NULL" : sqlStr(e.fromState),
      to_state: sqlStr(e.toState),
      '"by"': "NULL",
      reason: e.reason == null ? "NULL" : sqlStr(e.reason),
      at: sqlTs(e.at),
    })),
  ),
);

parts.push(`-- Explicitly skipped (auth / not in co_1 mock seed):
--   other demo companies and their branches
--   non-KW tax codes from the mock catalog
--   bill_4 / bill_4_l1 — blocked by UNIQUE (company_id, supplier_id, invoice_number)
--     (mock intentionally duplicates bill_1 vendor invoice number)
--   approval_requests, approval_steps, approval_decisions, notifications
--   user_profiles, company_members, invitations
--   price_lists, bank statements / reconciliation, period_close_*, fixed_assets
--   document_links (not present in mocks)
--   account_mappings: cash, wht_payable, retained_earnings, depreciation_expense,
--     accumulated_depreciation (no matching mock accounts)
`);

const sql = parts.join("");

// Strip SQL comments before forbidden-id checks so the skip list can mention them.
const sqlNoComments = sql.replace(/--[^\n]*/g, "");
const forbidden = [
  /SET\s+search_path/i,
  /set_config\s*\(/i,
  /current_setting\s*\(/i,
  /\bco_2\b/,
  /\bco_3\b/,
  /\bbr_2\b/,
  /\bbr_3\b/,
  /tax_sa_vat_15/,
  /tax_ae_vat_5/,
];
for (const re of forbidden) {
  if (re.test(sqlNoComments)) {
    throw new Error(`Generated SQL failed safety check: ${re}`);
  }
}

writeFileSync(OUT, sql, "utf8");
console.log(`Wrote ${OUT}`);
console.log(`Bytes: ${Buffer.byteLength(sql, "utf8")}`);
