/**
 * PDF generation service — ported from functions/pdf-gen (Deno → Node).
 * Black/white only, Arabic RTL, PDF/A-2b via pdfnative.
 */

import {
  buildDocumentPDFBytes,
  registerFonts,
  loadFontData,
  type DocumentBlock,
  type FontData,
  type FontEntry,
  type FontLoader,
  type PdfLayoutOptions,
} from "pdfnative";
import { createInsForgeServerClient } from "@/lib/insforge/server";
import type { ActionErrorCode } from "@/lib/actions/result";
import type {
  FinancialPdfType,
  PdfDocType,
  PdfMode,
  PdfResult,
  FunctionLocale,
} from "@/types/functions";

export type PdfClient = Awaited<ReturnType<typeof createInsForgeServerClient>>;

type DocType = PdfDocType | "financial";
type FinancialType = FinancialPdfType;
type PdfLocale = FunctionLocale;

export type DocPdfInput = {
  docType: PdfDocType;
  docId: string;
  locale: PdfLocale;
  mode: PdfMode;
};

export type FinancialPdfInput = {
  docType: "financial";
  type: FinancialType;
  periodId: string;
  locale: PdfLocale;
  mode: PdfMode;
};

export type PdfRequest = DocPdfInput | FinancialPdfInput;

type LineRow = {
  code: string;
  description: string;
  qty: number | string;
  unitPrice: number | string;
  total: number | string;
};

type DocData = {
  companyId: string;
  number: string;
  date: string;
  dueDate?: string;
  validUntil?: string;
  partyType: "customer" | "supplier";
  partyName: string;
  partyVat?: string;
  companyName: string;
  companyVat?: string;
  currency: string;
  lines: LineRow[];
  subtotal: number;
  taxTotal: number;
  total: number;
  notes?: string;
  state: string;
};

type FinancialData = {
  companyId: string;
  companyName: string;
  statementType: string;
  period: string;
  currency: string;
  lineItems: { label: string; amount: number }[];
  totals: Record<string, number>;
};

type Labels = {
  docType: string;
  number: string;
  date: string;
  dueDate: string;
  validUntil: string;
  customer: string;
  supplier: string;
  currency: string;
  colCode: string;
  colDescription: string;
  colQty: string;
  colUnitPrice: string;
  colTotal: string;
  subtotal: string;
  tax: string;
  total: string;
  footer: string;
  period: string;
  label: string;
  amount: string;
};

const EN: Labels = {
  docType: "Quote",
  number: "Number",
  date: "Date",
  dueDate: "Due date",
  validUntil: "Valid until",
  customer: "Customer",
  supplier: "Supplier",
  currency: "Currency",
  colCode: "Code",
  colDescription: "Description",
  colQty: "Qty",
  colUnitPrice: "Unit price",
  colTotal: "Total",
  subtotal: "Subtotal",
  tax: "Tax",
  total: "Total",
  footer: "Generated by Atmata ERP",
  period: "Period",
  label: "Label",
  amount: "Amount",
};

const AR: Labels = {
  docType: "عرض سعر",
  number: "الرقم",
  date: "التاريخ",
  dueDate: "تاريخ الاستحقاق",
  validUntil: "صالح حتى",
  customer: "العميل",
  supplier: "المورد",
  currency: "العملة",
  colCode: "الرمز",
  colDescription: "الوصف",
  colQty: "الكمية",
  colUnitPrice: "سعر الوحدة",
  colTotal: "الإجمالي",
  subtotal: "المجموع الفرعي",
  tax: "الضريبة",
  total: "الإجمالي",
  footer: "تم إنشاؤه بواسطة Atmata ERP",
  period: "الفترة",
  label: "البند",
  amount: "المبلغ",
};

function labelsFor(locale: PdfLocale): Labels {
  return locale === "ar" ? AR : EN;
}

function docTypeLabel(docType: string, locale: PdfLocale): string {
  const map: Record<string, string> = {
    quote: labelsFor(locale).docType,
    invoice: locale === "ar" ? "فاتورة" : "Invoice",
    delivery: locale === "ar" ? "إشعار تسليم" : "Delivery note",
    purchase_order: locale === "ar" ? "أمر شراء" : "Purchase order",
    vendor_bill: locale === "ar" ? "فاتورة المورد" : "Vendor bill",
    financial: locale === "ar" ? "القوائم المالية" : "Financial statement",
  };
  return map[docType] ?? labelsFor(locale).docType;
}

// ─── fonts (lazy per-locale; pdfnative bundled Noto data) ─────────────────

let fontsRegistered = false;

async function importFontModule(
  loader: () => Promise<Record<string, unknown>>,
): Promise<FontData> {
  const mod = await loader();
  // Named-export font modules are FontData-shaped; cast past .d.ts drift on markAnchors.
  return mod as unknown as FontData;
}

function ensureFontsRegistered(): void {
  if (fontsRegistered) return;
  const ar: FontLoader = () =>
    importFontModule(() => import("pdfnative/fonts/noto-arabic-data.js"));
  const latin: FontLoader = () =>
    importFontModule(() => import("pdfnative/fonts/noto-sans-data.js"));
  registerFonts({ ar, latin });
  fontsRegistered = true;
}

async function loadLocaleFonts(locale: PdfLocale): Promise<FontEntry[]> {
  ensureFontsRegistered();
  const latin = await loadFontData("latin");
  if (!latin) throw new Error("latin font failed to load");
  // /F1 and /F2 are reserved by pdfnative (base-14 fonts). Custom CIDFont
  // entries must use /F3+ with a leading slash.
  if (locale === "en") return [{ fontData: latin, fontRef: "/F3", lang: "latin" }];
  const ar = await loadFontData("ar");
  if (!ar) throw new Error("arabic font failed to load");
  return [
    { fontData: ar, fontRef: "/F4", lang: "ar" },
    { fontData: latin, fontRef: "/F3", lang: "latin" },
  ];
}

const BW = {
  black: "#000000" as const,
  gray: "#666666" as const,
  lightBorder: "#CCCCCC" as const,
  altRow: "#F5F5F5" as const,
  white: "#FFFFFF" as const,
};

function lineItemsTable(lines: LineRow[], L: Labels, isAr: boolean): DocumentBlock {
  const headers = isAr
    ? [L.colCode, L.colDescription, L.colQty, L.colUnitPrice, L.colTotal]
    : ["Code", "Description", "Qty", "Unit price", "Total"];
  return {
    type: "table",
    headers,
    rows: lines.map((l) => ({
      cells: [l.code, l.description, String(l.qty), String(l.unitPrice), String(l.total)],
      type: "",
      pointed: false,
    })),
    columns: [
      { f: 0.12, a: "l", mx: 24, mxH: 24 },
      { f: 0.4, a: "l", mx: 80, mxH: 24 },
      { f: 0.12, a: isAr ? "r" : "c", mx: 16, mxH: 16 },
      { f: 0.18, a: "r", mx: 24, mxH: 24 },
      { f: 0.18, a: "r", mx: 24, mxH: 24 },
    ],
  };
}

function partyBlock(data: DocData, L: Labels, isAr: boolean): DocumentBlock {
  const partyLabel = data.partyType === "supplier" ? L.supplier : L.customer;
  const dateLabel = data.dueDate ? L.dueDate : L.validUntil;
  const dateValue = data.dueDate ?? data.validUntil ?? data.date;
  const lines = [
    `${partyLabel}: ${data.partyName}`,
    data.partyVat ? `${L.currency}: ${data.currency}` : "",
    `${L.number}: ${data.number}`,
    `${L.date}: ${data.date}`,
    dateValue ? `${dateLabel}: ${dateValue}` : "",
  ].filter(Boolean);
  return {
    type: "paragraph",
    text: lines.join("  ·  "),
    align: isAr ? "right" : "left",
    color: BW.gray,
  };
}

function totalsBlock(data: DocData, L: Labels, isAr: boolean): DocumentBlock {
  return {
    type: "paragraph",
    text: [
      `${L.subtotal}: ${data.currency} ${data.subtotal}`,
      `${L.tax}: ${data.currency} ${data.taxTotal}`,
      `${L.total}: ${data.currency} ${data.total}`,
    ].join("  ·  "),
    align: isAr ? "right" : "left",
    color: BW.black,
  };
}

function buildDocBlocks(
  docType: string,
  data: DocData,
  L: Labels,
  locale: PdfLocale,
): DocumentBlock[] {
  const isAr = locale === "ar";
  const title = `${docTypeLabel(docType, locale)} ${data.number}`;
  const blocks: DocumentBlock[] = [
    { type: "heading", text: title, level: 1, color: BW.black },
    partyBlock(data, L, isAr),
    { type: "spacer", height: 12 },
    lineItemsTable(data.lines, L, isAr),
    { type: "spacer", height: 12 },
    totalsBlock(data, L, isAr),
  ];
  if (data.notes) blocks.push({ type: "paragraph", text: data.notes, color: BW.gray });
  blocks.push({ type: "paragraph", text: L.footer, color: BW.gray });
  return blocks;
}

function buildFinancialBlocks(
  data: FinancialData,
  L: Labels,
  locale: PdfLocale,
): DocumentBlock[] {
  const isAr = locale === "ar";
  return [
    { type: "heading", text: `${data.statementType} — ${data.period}`, level: 1, color: BW.black },
    {
      type: "paragraph",
      text: `${L.currency}: ${data.currency}`,
      align: isAr ? "right" : "left",
      color: BW.gray,
    },
    { type: "spacer", height: 12 },
    {
      type: "table",
      headers: isAr ? [L.label, L.amount] : ["Label", "Amount"],
      rows: data.lineItems.map((li) => ({
        cells: [li.label, String(li.amount)],
        type: "",
        pointed: false,
      })),
      columns: [
        { f: 0.6, a: "l", mx: 80, mxH: 24 },
        { f: 0.4, a: "r", mx: 32, mxH: 24 },
      ],
    },
    { type: "spacer", height: 12 },
    {
      type: "paragraph",
      text: Object.entries(data.totals)
        .map(([k, v]) => `${k}: ${data.currency} ${v}`)
        .join("  ·  "),
      align: isAr ? "right" : "left",
      color: BW.black,
    },
    { type: "paragraph", text: L.footer, color: BW.gray },
  ];
}

const TEMPLATE_VERSION = "sha256:9fa58346c397f250";

const BW_COLORS = {
  title: BW.black,
  credit: BW.black,
  debit: BW.black,
  text: BW.black,
  thBg: BW.white,
  thBrd: BW.black,
  rowBrd: BW.lightBorder,
  ptdBg: BW.white,
  balBg: BW.altRow,
  balBrd: BW.black,
  label: BW.gray,
  footer: BW.gray,
};

function pageHeader(title: string, companyName: string, isAr: boolean) {
  return {
    left: isAr ? "" : companyName,
    center: "",
    right: isAr ? companyName : title,
  };
}

function pageFooter(footerText: string) {
  return { left: footerText, right: "Page {page} of {pages}" };
}

async function renderDoc(docType: string, data: DocData, locale: PdfLocale): Promise<Uint8Array> {
  const L = labelsFor(locale);
  const isAr = locale === "ar";
  const title = `${docTypeLabel(docType, locale)} ${data.number}`;
  const blocks = buildDocBlocks(docType, data, L, locale);
  const fontEntries = await loadLocaleFonts(locale);
  const layout: Partial<PdfLayoutOptions> = {
    tagged: "pdfa2b",
    colors: BW_COLORS,
    headerTemplate: pageHeader(title, data.companyName, isAr),
    footerTemplate: pageFooter(L.footer),
    viewerPreferences: { direction: isAr ? "r2l" : "l2r" },
  };
  return buildDocumentPDFBytes(
    { title, blocks, footerText: L.footer, fontEntries },
    layout,
  );
}

async function renderFinancial(data: FinancialData, locale: PdfLocale): Promise<Uint8Array> {
  const L = labelsFor(locale);
  const isAr = locale === "ar";
  const title = `${data.statementType} — ${data.period}`;
  const blocks = buildFinancialBlocks(data, L, locale);
  const fontEntries = await loadLocaleFonts(locale);
  const layout: Partial<PdfLayoutOptions> = {
    tagged: "pdfa2b",
    colors: BW_COLORS,
    headerTemplate: pageHeader(title, data.companyName, isAr),
    footerTemplate: pageFooter(L.footer),
    viewerPreferences: { direction: isAr ? "r2l" : "l2r" },
  };
  return buildDocumentPDFBytes(
    { title, blocks, footerText: L.footer, fontEntries },
    layout,
  );
}

export class PdfServiceError extends Error {
  constructor(
    readonly code: Extract<
      ActionErrorCode,
      "NOT_FOUND" | "CONFLICT" | "STORAGE_FAILED" | "UNAVAILABLE" | "INTERNAL" | "UNAUTHENTICATED" | "VALIDATION"
    >,
    readonly status: number,
    readonly retryable = false,
  ) {
    super(code);
    this.name = "PdfServiceError";
  }
}

function camelize<T = Record<string, unknown>>(row: T): T {
  const out: Record<string, unknown> = {};
  for (const k of Object.keys(row as object)) {
    const camel = k.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
    out[camel] = (row as Record<string, unknown>)[k];
  }
  return out as T;
}

async function fetchOne<T = Record<string, unknown>>(
  c: PdfClient,
  table: string,
  id: string,
  select: string,
): Promise<T> {
  const { data, error } = await c.database.from(table).select(select).eq("id", id).single();
  if (error || !data) throw new PdfServiceError("NOT_FOUND", 404);
  return camelize(data as T);
}

async function fetchLines(
  c: PdfClient,
  lineTable: string,
  parentCol: string,
  docId: string,
): Promise<LineRow[]> {
  const { data, error } = await c.database
    .from(lineTable)
    .select("product_id, description, qty, qty_delivered, unit_price")
    .eq(parentCol, docId);
  if (error) throw new PdfServiceError("UNAVAILABLE", 503, true);
  const rows = (data ?? []) as Record<string, unknown>[];
  const productIds = [
    ...new Set(rows.map((row) => String(row.product_id ?? "")).filter(Boolean)),
  ];
  const productMap = new Map<string, { sku?: string; name?: string }>();
  if (productIds.length > 0) {
    const { data: products, error: productError } = await c.database
      .from("products")
      .select("id, sku, name")
      .in("id", productIds);
    if (productError) throw new PdfServiceError("UNAVAILABLE", 503, true);
    for (const product of products ?? []) {
      productMap.set(String((product as { id: string }).id), product as { sku?: string; name?: string });
    }
  }
  return rows.map((r) => {
    const row = camelize(r);
    const product = productMap.get(String(row.productId ?? ""));
    const qty = Number(row.qtyDelivered ?? row.qty ?? 0);
    const unitPrice = Number(row.unitPrice ?? 0);
    return {
      code: String(product?.sku ?? ""),
      description: String(row.description ?? product?.name ?? ""),
      qty,
      unitPrice,
      total: Number((Number(row.total ?? qty * unitPrice)).toFixed(3)),
    };
  });
}

const DOC_TABLEL: Record<PdfDocType, string> = {
  quote: "quotes",
  invoice: "customer_invoices",
  delivery: "delivery_notes",
  purchase_order: "purchase_orders",
  vendor_bill: "vendor_bills",
};

const LINE_TABLEL: Record<PdfDocType, string> = {
  quote: "quote_lines",
  invoice: "customer_invoice_lines",
  delivery: "delivery_note_lines",
  purchase_order: "purchase_order_lines",
  vendor_bill: "vendor_bill_lines",
};

const LINE_PARENT_COL: Record<PdfDocType, string> = {
  quote: "quote_id",
  invoice: "customer_invoice_id",
  delivery: "delivery_note_id",
  purchase_order: "purchase_order_id",
  vendor_bill: "vendor_bill_id",
};

const PARTY_TABLEL: Record<PdfDocType, "customers" | "suppliers"> = {
  quote: "customers",
  invoice: "customers",
  delivery: "customers",
  purchase_order: "suppliers",
  vendor_bill: "suppliers",
};

async function fetchDocData(
  c: PdfClient,
  docType: PdfDocType,
  docId: string,
): Promise<DocData> {
  const doc = await fetchOne<Record<string, unknown>>(c, DOC_TABLEL[docType], docId, "*");

  const [party, company, lines] = await Promise.all([
    fetchOne<Record<string, unknown>>(
      c,
      PARTY_TABLEL[docType],
      String(doc.customerId ?? doc.supplierId ?? ""),
      "id, name, vat_number",
    ),
    fetchOne<Record<string, unknown>>(
      c,
      "companies",
      String(doc.companyId ?? ""),
      "id, name, vat_number, base_currency",
    ),
    fetchLines(c, LINE_TABLEL[docType], LINE_PARENT_COL[docType], docId),
  ]);

  return {
    companyId: String(company.id ?? ""),
    number: String(doc.number ?? ""),
    date: String(doc.date ?? ""),
    dueDate: doc.dueDate ? String(doc.dueDate) : undefined,
    validUntil: doc.validUntil ? String(doc.validUntil) : undefined,
    partyType: PARTY_TABLEL[docType] === "suppliers" ? "supplier" : "customer",
    partyName: String(party.name ?? ""),
    partyVat: party.vatNumber ? String(party.vatNumber) : undefined,
    companyName: String(company.name ?? ""),
    companyVat: company.vatNumber ? String(company.vatNumber) : undefined,
    currency: String(doc.currency ?? company.baseCurrency ?? "KWD"),
    lines,
    subtotal: Number(doc.subtotal ?? 0),
    taxTotal: Number(doc.taxTotal ?? 0),
    total: Number(doc.total ?? 0),
    notes: doc.notes ? String(doc.notes) : undefined,
    state: String(doc.state ?? "draft"),
  };
}

async function fetchFinancialData(
  c: PdfClient,
  type: FinancialType,
  periodId: string,
): Promise<FinancialData> {
  const rpcName =
    type === "pl"
      ? "report_pnl"
      : type === "balance_sheet"
        ? "report_balance_sheet"
        : type === "cash_flow"
          ? "report_cash_flow"
          : "report_trial_balance";
  const { data, error } =
    type === "trial_balance"
      ? await c.database.rpc(rpcName)
      : await c.database.rpc(rpcName, { p_period_id: periodId });
  if (error || !data) throw new PdfServiceError("UNAVAILABLE", 503, true);

  const json =
    type === "trial_balance"
      ? {
          line_items: (data as Array<Record<string, unknown>>).map((row) => ({
            label: `${row.account_code ?? ""} ${row.account_name ?? ""}`.trim(),
            amount: Number(row.balance ?? 0),
          })),
          totals: {
            debit: (data as Array<Record<string, unknown>>).reduce(
              (sum, row) => sum + Number(row.debit ?? 0),
              0,
            ),
            credit: (data as Array<Record<string, unknown>>).reduce(
              (sum, row) => sum + Number(row.credit ?? 0),
              0,
            ),
          },
        }
      : (data as {
          line_items: { label: string; amount: number }[];
          totals: Record<string, number>;
        });

  const period = await fetchOne<{ year: number; month: number; companyId: string }>(
    c,
    "fiscal_periods",
    periodId,
    "year, month, company_id",
  );
  const company = await fetchOne<{ id: string; name: string; baseCurrency: string }>(
    c,
    "companies",
    period.companyId,
    "id, name, base_currency",
  );

  return {
    companyId: String(company.id),
    companyName: String(company.name),
    statementType:
      type === "pl"
        ? "Profit & Loss"
        : type === "balance_sheet"
          ? "Balance Sheet"
          : type === "cash_flow"
            ? "Cash Flow"
            : "Trial Balance",
    period: `${period.year}-${String(period.month).padStart(2, "0")}`,
    currency: String(company.baseCurrency ?? "KWD"),
    lineItems: json.line_items ?? [],
    totals: json.totals ?? {},
  };
}

function stableStringify(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  if (value && typeof value === "object") {
    return `{${Object.entries(value as Record<string, unknown>)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, item]) => `${JSON.stringify(key)}:${stableStringify(item)}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

async function hashData(value: unknown): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(stableStringify(value)),
  );
  return [...new Uint8Array(digest)]
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("")
    .slice(0, 24);
}

function bytesToBase64(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("base64");
}

async function handleSave(
  c: PdfClient,
  companyId: string,
  docType: string,
  docId: string,
  locale: PdfLocale,
  state: string,
  dataHash: string,
  bytes: Uint8Array,
): Promise<Extract<PdfResult, { mode: "save" }>> {
  const path = `${companyId}/${docType}/${docId}/pdf-${locale}-${state}-${TEMPLATE_VERSION.replace(":", "-")}-${dataHash}.pdf`;

  const findCached = async () => {
    const { data, error } = await c.database
      .from("attachments")
      .select("id, key")
      .eq("company_id", companyId)
      .eq("doc_type", docType)
      .eq("doc_id", docId)
      .eq("kind", "generated_pdf")
      .eq("template_version", TEMPLATE_VERSION)
      .eq("key", path)
      .maybeSingle();
    if (error) throw new PdfServiceError("UNAVAILABLE", 503, true);
    return data as { id: string; key: string } | null;
  };

  const signedResult = async (
    attachment: { id: string; key: string },
    cached: boolean,
  ): Promise<Extract<PdfResult, { mode: "save" }>> => {
    const { data: signed, error: signedError } = await c.storage
      .from("documents")
      .createSignedUrl(attachment.key, 3600);
    if (signedError || !signed) throw new PdfServiceError("STORAGE_FAILED", 502, true);
    return {
      mode: "save",
      attachmentId: attachment.id,
      url: signed.signedUrl,
      key: attachment.key,
      cached,
    };
  };

  const existing = await findCached();
  if (existing) return signedResult(existing, true);

  const { data: up, error: upErr } = await c.storage
    .from("documents")
    .upload(path, new Blob([Buffer.from(bytes)], { type: "application/pdf" }));
  if (upErr || !up) throw new PdfServiceError("STORAGE_FAILED", 502, true);

  if (up.key !== path) {
    for (let attempt = 0; attempt < 4; attempt += 1) {
      await new Promise((resolve) => setTimeout(resolve, 75 * (attempt + 1)));
      const winner = await findCached();
      if (winner) {
        await c.storage.from("documents").remove(up.key);
        return signedResult(winner, true);
      }
    }
    await c.storage.from("documents").remove(up.key);
    throw new PdfServiceError("CONFLICT", 409, true);
  }

  const { data: att, error: attErr } = await c.database
    .from("attachments")
    .insert([
      {
        company_id: companyId,
        doc_type: docType,
        doc_id: docId,
        bucket: "documents",
        key: path,
        url: up.url,
        mime: "application/pdf",
        size: bytes.length,
        kind: "generated_pdf",
        template_version: TEMPLATE_VERSION,
      },
    ])
    .select("id")
    .single();
  if (attErr || !att) {
    const winner = await findCached();
    if (winner) return signedResult(winner, true);
    throw new PdfServiceError("CONFLICT", 409, true);
  }
  return signedResult({ id: (att as { id: string }).id, key: path }, false);
}

const DOC_TYPES = new Set<string>([
  "quote",
  "invoice",
  "delivery",
  "purchase_order",
  "vendor_bill",
]);
const FINANCIAL_TYPES = new Set<string>([
  "pl",
  "balance_sheet",
  "cash_flow",
  "trial_balance",
]);

export function parsePdfRequest(value: unknown): PdfRequest | null {
  if (!value || typeof value !== "object") return null;
  const body = value as Record<string, unknown>;
  if (
    (body.locale !== "en" && body.locale !== "ar") ||
    (body.mode !== "preview" && body.mode !== "save")
  ) {
    return null;
  }
  if (body.docType === "financial") {
    if (
      typeof body.type !== "string" ||
      !FINANCIAL_TYPES.has(body.type) ||
      typeof body.periodId !== "string" ||
      body.periodId.length < 1 ||
      body.periodId.length > 160
    ) {
      return null;
    }
    return body as FinancialPdfInput;
  }
  if (
    typeof body.docType !== "string" ||
    !DOC_TYPES.has(body.docType) ||
    typeof body.docId !== "string" ||
    body.docId.length < 1 ||
    body.docId.length > 160
  ) {
    return null;
  }
  return body as DocPdfInput;
}

function isFinancialInput(body: PdfRequest): body is FinancialPdfInput {
  return body.docType === "financial";
}

/**
 * Generate a PDF for a document or financial report.
 *
 * TODO(phase2-jobs): `enqueueJob('pdf', …)` exists in `@/lib/jobs`, but the
 * pdf worker handler is still a stub and DocPdfActions expects a signed URL
 * immediately. Keep financial `mode: "save"` sync until a pdf handler + UI
 * job-status poll lands, then enqueue heavy reports and return `{ jobId }`.
 */
export async function generatePdf(
  body: PdfRequest,
  client?: PdfClient,
  opts?: { requireUser?: boolean },
): Promise<PdfResult> {
  const c = client ?? (await createInsForgeServerClient());
  const requireUser = opts?.requireUser !== false;
  if (requireUser) {
    const { data: userData } = await c.auth.getCurrentUser();
    if (!userData?.user?.id) throw new PdfServiceError("UNAUTHENTICATED", 401);
  }

  if (isFinancialInput(body)) {
    const data = await fetchFinancialData(c, body.type, body.periodId);
    const bytes = await renderFinancial(data, body.locale);
    if (body.mode === "preview") {
      return {
        mode: "preview",
        contentType: "application/pdf",
        base64: bytesToBase64(bytes),
      };
    }
    // Sync save — see TODO above (pdf job handler + UI poll not ready).
    return handleSave(
      c,
      data.companyId,
      "financial",
      body.periodId,
      body.locale,
      "posted",
      await hashData(data),
      bytes,
    );
  }

  const data = await fetchDocData(c, body.docType, body.docId);
  const bytes = await renderDoc(body.docType, data, body.locale);
  if (body.mode === "preview") {
    return {
      mode: "preview",
      contentType: "application/pdf",
      base64: bytesToBase64(bytes),
    };
  }
  return handleSave(
    c,
    data.companyId,
    body.docType,
    body.docId,
    body.locale,
    data.state,
    await hashData(data),
    bytes,
  );
}

export type { DocType };
